% Template of a file to indicate what you want done (LI only)
% 
% Integrated Brain Analysis Toolbox for SPM: 'runinfo_li_template.m'
% Template version date: 2024-10-26
%
% See also README_Laterality.txt for a quick-start guide to usage.
%
% To execute this script, either select run from the iBT 
% menu or type ibt directly at the Matlab command line; you will
% then be prompted to select a runinfo file to execute.
%
% This is the file to edit to indicate what you want done, designed
% to perform an analysis of laterality only. It is a stripped-down version
% of a full runinfo template, with changes made so that it does 
% not require the original or pre-processed data. Only the statistical
% results are required. You may wish to use this stripped-down
% version if your data was generated outside of the Integrated Brain Analysis
% Toolbox for SPM. If you are generating data within the toolbox then
% it is easier to specify the laterality calculation in the full
% version of the runinfo.
%
% This runinfo is designed for use with the Integrated Brain Analysis
% Toolbox for SPM (iBT), which incorporates all the functionality of
% the previously released iBrain Laterality Toolbox.
%
% The Laterality scripts use some SPM functions, however the
% data on which they operate need not have been generated by SPM.
%
% The laterality graphing function by default makes use of jbtest,
% which requires the Matlab Statistics Toolbox. This can be disabled
% if required by setting iBT.what.li.jb_alpha to 0.
%
% Do not use - or . in the filename of this runinfo file, otherwise
% Matlab will have trouble finding it.
%
% Only the iBT structure is passed to other scripts: all other variables
% and code here are for convenience when setting up iBT.

%___________________________________________________________________________
% Copyright 2009-2014,2017,2018,2020,2024 The Florey Institute 
%                               of Neuroscience and Mental Health
% David Abbott
%
% This file is part of iBT (the Integrated Brain Analysis Toolbox for SPM).
% See README_iBT.txt and README_Laterality.txt for more information.
%
% Please refer to the following paper for a description of the laterality
% methods implemented in this toolbox. If you publish results using
% these methods or variations of them, please remember to cite this paper: 
%     Abbott DF, Waites AB, Lillywhite LM, Jackson GD.
%     fMRI assessment of language lateralization: An objective approach. 
%     Neuroimage 50(4):1446-1455 (2010).
%
% iBT is free software: you can redistribute it and/or modify it under the
% terms of the GNU General Public License as published by the Free Software
% Foundation, either version 3 of the License, or (at your option) any later
% version.
% ___________________________________________________________________________
%

spm('defaults','fmri');
iBT.what.SpmVersion = spm('Ver');

% Use appropriate version of SPM template extension
switch(iBT.what.SpmVersion),
        case {'SPM2','SPM5','SPM8'}
                stats_ext = '.img';
        otherwise %SPM12 or later
                stats_ext = '.nii';
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 1: data/subject info: the WHO
%
% location of data, analysis directories, etc.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% The following can help avoid accidentally running this script in an unintended SPM version:
iBT.what.prefer.SPM = 'SPM12'; % Preferred SPM version for this script (e.g. 'SPM12b'; warns if not exact match). '' or comment out for no preference.

% (usually put the scripts in the analysis working directory, and analysis results will be saved in subdirectories thereunder)
iBT.what.where.awd = pwd ; % Analysis working directory: pwd (without quotes) uses the current directory. 
			   % Otherwise specify an explicit path with a string in quotes, e.g. '/home/username/analysis'

% You can either set up specific study details here, or by reference to another file.
% Choose by uncommenting one only of the following lines:
studylistfile='studylist_li.txt'; % non-blank string indicates read in details from file.
%studylistfile=''; % Blank string indicates setup within current runinfo file only


if strcmp(studylistfile,'') == 1 % Set up all details here if we're not reading a study-list file


sub=1;
iBT.who.sub{sub}.ID = 'Test01'; % Subject ID - Analysis subdirectory and contrast names will use this
iBT.who.sub{sub}.sess{1}.spmloc='/data/user/statistical_analysis/subject_name/pseudoword';% Location of statistical map images
% or you could dynamically embed SPM version and use platform-independent file separators as follows:
% iBT.who.sub{sub}.sess{1}.spmloc=fullfile(filesep, 'data', 'user', [iBT.what.SpmVersion '_analysis'],'subject_name', 'pseudoword');% Location of statistical map images
iBT.who.sub{sub}.sess{1}.task='pseudoword';  %name for the task

% sub = sub +1;
% You can specify the next subject using similar variables to those for first
% etc (this script will loop through multiple sessions and subjects if specified). 



else %  studylistfile is not empty, so read multiple study details in from that file
% The file must contain one line per session with the following three or more space-separated fields:
% sub spmloc task
% Comment lines beginning with a # are permitted, as are filenames with spaces if quoted.
%

 f = fopen(studylistfile);             
   s = textscan(f,'%s','delimiter','\r\n','CommentStyle', '#'); % Read the whole file into variable s, with each line a separate cell, ignoring comments
 fclose(f);
 s = cellstr(s{1});
 num_rows = size(s,1);

 IDcol=1;spmlocCol=2;taskCol=3;
 sub=0; %We increment on first pass through loop, so will count from 1.
 last_ID='';
 x=0;y=0;z=0; % initialise in case not present.
 for i=1:num_rows,
   if size(s{i},1) > 0
     studyLine=textscan(s{i},'%q','CommentStyle', '#'); % Read text of each line into separate fields (supports quoting of delimiter characters)
     studyLine=studyLine{1};
   else studyLine=''; end;
   num_cols=size(studyLine,1);
   if num_cols >= 3,
     ID = studyLine{IDcol};
     if strcmp(ID,last_ID)==0 
   	sub = sub + 1; last_ID = ID; ses=1; 
     else
   	ses = ses+1;
     end
     spmloc = studyLine{spmlocCol};
     task = studyLine{taskCol};
   
     iBT.who.sub{sub}.ID = ID;
     iBT.who.sub{sub}.sess{ses}.spmloc = spmloc;
     iBT.who.sub{sub}.sess{ses}.task = task;
     disp(sprintf('Successfully loaded instructions for subject %i. ',sub));
   elseif num_cols > 0 
     error(sprintf('Error: line %i of studylist file %s has only %i fields (expected at least 3).',i,studylistfile,num_cols));
   end %if num_cols >= 3 elseif num_cols > 0
 end % for
 pause(2); % Give the user a couple of seconds to see how many subjects and sessions we found in the studylist.
end % if read_study_list_file


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 2: input choices
%
% specify WHAT you want to do
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


iBT.what.li.do=1; % Determine laterality indices: 1(yes) 0(no)
	iBT.what.li.wild=['spmT_????' stats_ext]; % Wildcard of the statistic image(s) for which to calculate laterality. e.g. ['spmT_????.nii']
		% Be careful to maintain consistency with control data - see also iBT.what.li.control_index_mapping
	iBT.what.li.roi_dir='/data/LI/ROIs/'; % where the left and right ROI images are located
 	iBT.what.li.left_roi='left_cortical_ROI_mask.img';  % filename of the left (or typically dominant) ROI image
	iBT.what.li.right_roi='right_cortical_ROI_mask.img'; % filename of the right (or typically non-dominant) ROI image
	iBT.what.li.save.mat=1; % Write LI data as a mat file: 1(yes) 0(no)
	iBT.what.li.save.text=0; % Write LI data as an Excel readable text file: 1(yes) 0(no)
	iBT.what.li.save.path = fullfile(pwd,'li_data'); % Where to save output files. Default if not set is in each individual's spm folder.
	iBT.what.li.reuse_existing = 1; % If set and a previous compatible li_active*.mat file exists, script will read it rather than re-calculating LIs.
	iBT.what.li.do_graph=1; % Plot LI data: 1(yes) 0(no)
	  iBT.what.li.save.graph = 1; % Save the plot(s): 1(yes) 0(no) (requires iBT.what.li.do_graph)
	  iBT.what.li.save.thresh=1; % Write the adaptive minimum valid Nvox t-threshold to a mat file for subsequent 
	  			 % use by batch_maps: 1(yes) 0(no)
	  iBT.what.li.control_dir='/data/LI/group_LIs/li_data_control_group'; % where previously calculated LI mat files are located -  
	  		; % include in plot as controls. Leave this blank if you haven't yet generated the control data.
	  iBT.what.li.control_wild='li_active*.mat'; % wildcard for the previously calculated LI mat files
	  iBT.what.li.conclusion.do=1; % Show conclusion (typical or atypical) prominently on summary plot: 1(yes) 0(no)
	  iBT.what.li.sanity.do=1; % Display the t and LI at the min nVox in the valid control range, and 
	  	% perform a sanity check of the data. The subject may not have performed the correct task if the 
	  	% deactivation appears to be more significant than the activation.  This is assessed by comparing, 
		% between activation and deactivation, the t-value corresponding to the the Nvox threshold at the minimum of the
		% valid group range. This assumes that the first contrast is the activation and the second the deactivation.
%	   iBT.what.li.control_index_mapping=[ 2 1 ]; % Uncomment to change index mapping between previously calculated LI mat files and 
	     ; % current analysis order. e.g. if when calculating the control li mat files the analysis and the iBT.what.li.wild were such that
	     ; % a positive contrast was evaluated first followed by a negative contrast, and the current analysis has the contrasts
	     ; % in the reverse order (or perhaps you just want to evaluate the negative and so set iBT.what.li.wild to just match that) 
	     ; % then you will need to set iBT.what.li.control_index_mapping=[ 2 1 ] so that the current first
	     ; % contrast is compared to the control contrast 2 and the second to control contrast 1. Can also use this to map multiple
	     ; % contrasts to a single control contrast (perhaps you have two sessions of the same thing). e.g [ 1 1 2 1] would compare 
	     ; % each of the first, second and fourth contrasts of the current analysis to the first contrast of the control data, and
	     ; % the third contrast of the current analysis to the second contrast of the control data.
	
% End of iBT.what.li section




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 3: defaults
%
% Assumptions/options in the stages...
% bits you probably don't need to change
% (some settings here may not actually be used
%  if the relevant flag above has not been set)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%  Laterality
	iBT.what.li.li_only = 1; % This flag tells batch that we are running from the
			     % stripped-down laterality-only runinfo, so no need to start the SPM GUI.
	% iBT.what.li.SummaryPlot.show100 = 0; % 1(yes, display LIx100 (i.e. %) on the body of the summary plot) 0(no, display regular LI on the body of the plot (default) ) 
	iBT.what.li.nvox_step = 10; % Increment for number of voxel threshold
	iBT.what.li.thresh_step = 0.1; % Increment for t-value threshold
	% If iBT.what.li.do_graph is set, the following options can be used change defaults:
	% iBT.what.li.lowNpercentOffCeiling = 95; % Percentage of subjects that must have |LI| less than ceiling in "valid" region. Set to 0 for no constraint (default)
	% iBT.what.li.ceiling = 1.0; % Ceiling LI value for lowNpercentOffCeiling test above. Default = 1.0
	% iBT.what.li.jb_alpha = 0; %  Alpha value for the Jarque-Bera normality test. Default = 0.05. Set to 0 for no normality constraint. 
	% iBT.what.li.do_tgraph=1; % In addition to the default LI vs Nvoxel plots, also plot LI against t-threshold,
	                       % (these were used in the paper for comparison - you probably don't want this!): 1(yes) 0(no)
	% iBT.what.li.PlotJB=0; % Plot a representation of the Jarque-Bera values on the full plot (they will be green)
	% iBT.what.li.maxNvox=0; % full nvox plot maximum value, 0=Unlimited
	iBT.what.li.maxT=10; % full t-thresh plot maximum value, 0=Unlimited 	  

	% iBT.what.li.errorbars=1; % Plot group 95% CI as errorbars: 1(yes) 0(no,default)
	% iBT.what.li.CI95shading=0.85; % Shade outside group 95% CI (Grey value of shading ranging from 0=black to 1=none)
	% iBT.what.li.CI99shading=0.8; % Shade outside group 99% CI in full plot (Grey value of shading ranging from 0=black to 1=none) 
	% iBT.what.li.InvalidShading=0.9; % Shade outside valid area (Grey value of shading ranging from 0=black to 1=none) 
	iBT.what.li.FullPlot.AllY = 1; % Force full plot yrange from -1 to 1: 1(yes) 0(no - use automatic range)
	iBT.what.li.SummaryPlot.AllY = 1; % Force summary plot yrange from -1 to 1: 1(yes) 0(no - use automatic range)
				    % (this is forced to 1 if iBT.what.li.conclusion.do==1 to provide room for text)
	iBT.what.li.SummaryPlot.in_range_only=2; % If there is a valid range, then plot summary within that range?
		% -1(no, plot summary over same range as full plot).
		% 0(no, plot summary from 0 to max of valid range)
		% 1(yes, plot summary within valid range only).
		% 2(no, plot a portion of the invalid range as well ).
	  % The following settings determine what portion of the invalid range is
	  % also displayed if iBT.what.li.summary_plot_in_range_only=2:
	  iBT.what.li.SummaryPlot.lower_range_fraction = 2/3; % Plot this proportion of the lower invalid range (0 = none, 1 = all) 
	  iBT.what.li.SummaryPlot.upper_range_fraction = 2/3; % Plot whilst this fraction of control subjects still has data (0 = plot all)
	% iBT.what.li.RGB.GroupMean=[0 0 0]; % (all 0 is black) % Colour of the control group mean plot (default [0 1 1] which is cyan)
	 % iBT.what.li.LineStyle.GroupMean='-' % Style of the control group mean plot (default '-' which is a solid line)
	% iBT.what.li.RGB.GroupControls=[0.1 0.1 0.1] % (all 0.1 is very dark grey) % Colour of subjects in the control group (default [0.4 1 1] which is a bit lighter cyan)
     % iBT.what.li.LineStyle.GroupControls='--' % Line style of subjects in the control group (default '--' which is dashed)
	%iBT.what.li.RGB.Individual=[1 0 0]; % Colour of the individual subject (default [1 0 0] which is red)
	 %iBT.what.li.LineStyle.Individual='-';  % Line style of the individual subject (default '-' which is a solid line)
	%iBT.what.li.LineWidth.Default=2; % Default if not specified is 1.
	 %iBT.what.li.LineWidth.Individual=2; % Default if not specified is 1.
	%iBT.what.li.SummaryPlot.LineWidth.Default=3; % Default is iBT.what.li.LineWidth.Default
	 %iBT.what.li.SummaryPlot.LineWidth.Individual=3 % Default is iBT.what.li.SummaryPlot.LineWidth.Default
	%iBT.what.li.SummaryPlot.LIpoint=1; % Plot a marker on summary plot at point the stated LI is determined for the individual: 1(yes), 0(no, default) 
	 %iBT.what.li.SummaryPlot.RGB.LIpoint=[1 0 0]; % Colour of the LI point marker on the summary plot; default is iBT.what.li.RGB.Individual
	 %iBT.what.li.SummaryPlot.LineWidth.LIpoint = 3; % Default is 1
     %iBT.what.li.SummaryPlot.MarkerSize.LIpoint=12; % Radius of the circle in the marker; Default is 5

	 %iBT.what.li.PlotGroupOnly=1;% Don't plot the individual - just plot the group (was useful for a figure for the paper).
	                          % This also enables plotting all group data on the summary plot in addition to the full plot.

	  %iBT.what.li.FullPlot.Title=['Enter custom plot title here'];% Uncomment to force title of the plot.
	  %iBT.what.li.FullPlot.fileIDstring=['Enter custom filename here'];% Uncomment to force filename of the plot.
	  iBT.what.li.FullPlot.Box=1; % include a box with tick marks around the plot, 1(yes) 0(no)
	  %iBT.what.li.SummaryPlot.Title=iBT.what.li.FullPlot.Title;% Force title of the plot.
	  %iBT.what.li.SummaryPlot.fileIDstring=iBT.what.li.FullPlot.fileIDstring;% Uncomment to force filename of the plot..
	  iBT.what.li.SummaryPlot.Box=1; % include a box with tick marks around the plot, 1(yes) 0(no)
	  %iBT.what.li.SummaryPlot.RGB.GroupMean=[0.7 0.7 0.7]; % Colour of the control group mean on the summary plot (default same as detailed plot)
	  %iBT.what.li.SummaryPlot.LineStyle.GroupMean='--'; % Style of the control group mean on summary plot (default same as detailed plot)	
	  %iBT.what.li.SummaryPlot.typicalString=' ';  % Default if commented out is 'Conclusion: typical'
	  %iBT.what.li.SummaryPlot.atypicalString=' '; % Default if commented out is 'Conclusion: atypical'
