% Integrated Brain Analysis Toolbox for SPM: 'runinfo_other_display_template.m'
% Template version date: 2025-12-27
%
% Template of a file to indicate what you want done (cut-down version for
% display of results that have not been automatically generated with iBT).
% 
% To execute this script, either select run from the iBT 
% menu or type ibt directly at the Matlab command line; you will
% then be prompted to select a runinfo file to execute.
%
% Do not use - or . in the filename of this file, otherwise Matlab
% will have trouble finding it.
%
% Only the iBT structure is actually passed to other scripts;
% all other variables & code here are for convenience
% to set up iBT.
%

%_______________________________________________________________________________
% Copyright (C) 2004-2025 The Florey Institute of Neuroscience and Mental Health
% David Abbott
%
% This file is part of iBT (the Integrated Brain Analysis Toolbox for SPM).
% See README_iBT.txt for more information.
%
% iBT is free software: you can redistribute it and/or modify it under the
% terms of the GNU General Public License as published by the Free Software
% Foundation, either version 3 of the License, or (at your option) any later
% version.
%_______________________________________________________________________________
%


spm('defaults','fmri');
iBT.what.SpmVersion = spm('Ver');

iBT.what.FSL.ext = '.nii'; % Used for images generated by MELODIC - change if necessary to suit your environment.
iBT.what.iB.ext = '.img';  % Used for images generated by the standalone iBrain program

% Set image extension appropriate to SPM version:
switch(iBT.what.SpmVersion),
        case {'SPM2','SPM5','SPM8'}
                iBT.what.SPM.ext = '.img';
        otherwise
                iBT.what.SPM.ext = '.nii';
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 1: data/subject info: the WHO
%
% location of data, analysis directories, etc.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% The following can help avoid accidentally running this script in an unintended SPM version:
iBT.what.prefer.SPM = 'SPM12'; % Preferred SPM version for this script (e.g. 'SPM12b'; warns if not exact match). '' or comment out for no preference.

% (usually put the scripts in the analysis working directory, and analysis results will be saved in subdirectories thereunder)
iBT.what.where.awd = pwd ; % Analysis working directory: pwd (without quotes) uses the current directory. 
			   % Otherwise specify an explicit path with a string in quotes, e.g. '/home/username/analysis'

% Please do NOT use spaces in processed pathnames!

% You can either set up specific study details here, or by reference to another file.
% Choose by uncommenting one only of the following lines:
%studylistfile='studylist_other_display.txt'; % non-blank string indicates read in details from file.
studylistfile=''; % Blank string indicates setup within current runinfo file only


if strcmp(studylistfile,'') == 1 % Set up all details here if we're not reading a study-list file


sub=1;
ses=1;
iBT.who.sub{sub}.ID = 'TEST'; % Subject ID - Analysis subdirectory and contrast names will use this
iBT.who.sub{sub}.sess{ses}.disp.loc=fullfile(iBT.what.where.awd, 'RFX',  iBT.who.sub{sub}.ID); % Used only if iBT.what.disp.OTHER.do > 0. See note below.
iBT.who.sub{sub}.sess{ses}.task='OLR';  %name for the task

% sub = sub + 1; ses = 1;
% or
% ses = ses + 1;
% You can specify the next subject and/or session using similar variables 
% to those for first. Just makes sure sub and ses are set to the next
% session or subject and copy and paste the iBT.who.sub{sub}.sess{ses}
% variables above to a new sub and ses below

% Note on iBT.who.sub{sub}.sess{ses}.disp.loc: This can be used to facilitate
% automated display of one or more random effects (RFX) or other arbitrary
% analyses (see also iBT.what.disp.OTHER.do )
% Presently the toolbox does not perform 2nd level statistical analyses 
% automatically, but it can assist with display of the results of a 
% manually-generated 2nd level analysis. It is best to make a separate 
% runinfo for this purpose: You can use the {sub} index to loop through 
% the locations of different group analyses (for example, we've used this
% to generate summary images of several group random effects analyses that
% were conducted for different seed voxel locations in a series of 
% functional connectivity analyses). Optionally, to have informatively labeled
% display pages, you can have a _header_info.txt file in each folder.
% 


else %  studylistfile is not empty, so read multiple study details in from that file
% The file must contain one line per session with the following three or more space-separated fields:
% subID disploc task
% Comment lines beginning with a # are permitted, as are filenames with spaces if quoted.
% The little section below is Matlab code that reads in the studylist files. You will
% not need to modify this code unless you want to customise the format of the studylist file.

 f = fopen(studylistfile);             
   s = textscan(f,'%s','delimiter','\r\n','CommentStyle', '#'); % Read the whole file into variable s, with each line a separate cell, ignoring comments
 fclose(f);
 s = cellstr(s{1});
 num_rows = size(s,1);

 IDcol=1;dispCol=2;taskCol=3;
 sub=0; %We increment on first pass through loop, so will count from 1.
 last_ID='';
 x=0;y=0;z=0; % initialise in case not present.
 for i=1:num_rows,
   if size(s{i},1) > 0
     studyLine=textscan(s{i},'%q','CommentStyle', '#'); % Read text of each line into separate fields (supports quoting of delimiter characters)
     studyLine=studyLine{1};
   else studyLine=''; end;
   num_cols=size(studyLine,1);
   if num_cols >= 3,
     ID = studyLine{IDcol};
     if strcmp(ID,last_ID)==0 
   	sub = sub + 1; last_ID = ID; ses=1; 
     else
   	ses = ses+1;
     end
     disploc = studyLine{dispCol};
     task = studyLine{taskCol};
   
     iBT.who.sub{sub}.ID = ID;
     iBT.who.sub{sub}.sess{ses}.disp.loc = disploc; % Used only if iBT.what.disp.OTHER.do > 0. See note below.
     iBT.who.sub{sub}.sess{ses}.task = task;
     disp(sprintf('Successfully loaded instructions for subject %i. ',sub));
   elseif num_cols > 0 
     error(sprintf('Error: line %i of studylist file %s has only %i fields (expected at least 3).',i,studylistfile,num_cols));
   end %if num_cols >= 3 elseif num_cols > 0
 end % for
 pause(2); % Give the user a couple of seconds to see how many subjects and sessions we found in the studylist.
end % if read_study_list_file


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 2: input choices
%
% specify WHAT you want to do
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


iBT.what.disp.do = 1; %Generate summary images: 1(yes) 0(no)
	iBT.what.disp.OTHER.do = 1;	% Display data from a manually generated analysis (need not be from SPM): 0(no) 1(yes) 2(RFX)
					%  (Use iBT.who.sub{sub}.sess{ses}.disp.loc to specify location of the data for each 
					%   analysis - can loop over sub as a surrogate for studies)
	   iBT.what.disp.OTHER.title = 'RFX group analysis'; % Change this to whatever is appropriate.
	iBT.what.disp.output_parent_folder = ''; % Set this to something other than '' (e.g. iBT.what.where.awd ) to save the displayed 
		% results in a location separate from the analysis. A folder tree (excluding drive letter if present on 
		% Windows platforms) is then constructed in output_parent_folder that matches the path
		% in which the files would have been saved. For example, if the results would have been 
		% saved in "C:\data\subject2\stats\" and iBT.what.disp.output_parent folder is set to 
		% "D:\display" then results will be saved in  "D:\display\data\subject2\stats\"
	iBT.what.disp.orient.LeftOnRight = 'yes';  % yes = Radiological, no = Neurological orientation display
	iBT.what.disp.orient.showText = 1; % show text to indicate orientation (assumes RAS +ve): 1(yes, default), 0(no)
    iBT.what.disp.orient.transform = {'axial' 'coronal' 'sagittal'}; % Image orientation for the activation map (axial, coronal, sagittal)
%    iBT.what.disp.orient.slices = {84:-6:-66 78:-6:-108 78:-6:-78};  % Slice range corresponding to above orientations (ie. first transform
                         	                                     % uses first slice range, second transform uses second slice range etc
	iBT.what.disp.orient.slices = {88:-8:-72 72:-8:-96 64:-8:-64}; % This is better for 8mm smooth
	% Some other examples:
	% For own-space non-smoothed 64x64x35 with 3.43750 x 3.43752 x 3.4mm voxels:
%        iBT.what.disp.orient.slices = {57.8:-3.4:-57.8 108.280935:-3.437490:-108.280935 108.28125:-3.43750:-108.28125 }; % slice range corresponding to original own-space slices
	% This is because when origin not set, SPM8 assumes (32.5,32.5,18) for a 64x64x35 matrix; i.e. ((voxels-1)/2)+1
	% and to minimise display partial voluming, want slice position to be co-incident with a voxel (i.e. integer voxel value)
	% Thus for Z (axial slices) calculate +- range as (35 - 1) slice spacings x 3.4mm / 2 = 57.8.
	% Similarly 63 * 3.43750 / 2 = 108.28125 (X = sagittal)
	% 63 * 3.437490 / 2 = 108.280935 (Y = Coronal)
	%
	% For 44 slices @ 3.0mm, then for Z (axial slices) calculate +- range as (44 - 1) slice spacings x 3mm / 2 = 64.5
	% If 72 x 72 matrix @ 3mm, then for coronal and sag calculate +- range as (64 - 1) slice spacings x 3mm / 2 = 94.5
%        iBT.what.disp.orient.slices = {64.5:-3:-64.5 94.5:-3:-94.5 94.5:-3:-94.5};  % slice range corresponding to original own-space slices
	%
	% Notice that for axes with an even number of voxels, the slice 
	% selection will not include 0mm (as that would be between two slices).
	% Despite this, any sort of interpolation will introduce partial 
	% voluming so along with careful slice selection you probably also 
	% want to set iBT.what.disp.resample = 0 below (to force nearest neighbour resampling).
	%
	iBT.what.disp.statistic='Z'; % Text label for the statistic being displayed
	iBT.what.disp.threshold.type =     {'t'       't'}; % The type of threshold for OTHER display must be set to 't', indicating
	    % thresholding of statistic values as-is (without any additional probability calculation). You can can specify 't' even if the
	    % statistic image is not actually a t-statistic - see also iBT.what.disp.statistic above for correct labelling of the display.
	  % The following three cells must have at least as many elements as iBT.what.disp.threshold.type; any extra elements are ignored:
	  iBT.what.disp.threshold.thresh = {0         3.1      }; % lower threshold for magnitude of statistics (0 for no threshold)
	  iBT.what.disp.threshold.mini =   {0.000001  0.000001 }; % minimum value on colour scale (must be greater than zero to see background )
	  iBT.what.disp.threshold.maxi =   {8         8        }; % maximum value on colour scale
	iBT.what.disp.structural = 'wmean_all.img'; % Structural image filename. If not fully qualified, will search in present folder and iBT.who.sub{sub}.sess{ses}.disp.loc
	  %iBT.what.disp.structuralLabel = 'Mean of EPI time series'; % Optional description of the structural image to be used (rather than displaying the filename)
 	iBT.what.disp.contrast = 'spmT_????.img';   % Filename of statistical image(s) to display, e.g.'spmT_0003.img' (wildcards are allowed) 
	iBT.what.disp.contrastMissingOK = 0;   % Ignore the contrast and return without error if a matching file is not found: 1(yes) 0(no)
	iBT.what.disp.positive = 1; % Display positive values: 1(yes) 0(no)
	iBT.what.disp.negative = 1; % Display negative values: 1(yes) 0(no)
	iBT.what.disp.together = 1; % If both iBT.what.disp.positive and negative, create: 0(separate maps only), 1(default: one map with both + and - together), 2(both separate and together maps)
	iBT.what.disp.invert = 0; % Display positive values in cool colours, negative in warm colours: 0(no, default), 1(yes), 2(yes for -effect contrasts only)			  
				  % Note: If you specify 1 for both iBT.what.disp.positive and iBT.what.disp.negative and 2 for iBT.what.disp.invert
				  % then the display of +effect and -effect contrasts may appear to be identical (the only difference will be the 
				  % sign of the values on the colour scale). The option 2 is particularly useful when creating FDRc or FWEc maps 
				  % of -effects since only the positive tail can presently be displayed for cluster-corrected maps.
	iBT.what.disp.ROI.img = ''; % optionally specify a fully-qualified filename of a region-of-interest image to highlight a region on the image
	iBT.what.disp.resample = 0; % Resampling order for image (see hold argument to spm_sample_vol) - 0 = nearest neighbour, 1 (default) = trilinear,
				    % 2->127 = Higher order Lagrange (polynomial), -127 - -1 =  Different orders of sinc interpolation.
        iBT.what.disp.postscript = 0;      % PostScript file: 0 (none), 1 (truncate the existing file) or 2 (append to the existing file)
	iBT.what.disp.hideName = 0;	       % use the iBT.who.sub.ID rather than subject name for display headings (see also hideHeaderID) 1(yes) 0(no)
	iBT.what.disp.hideHeaderID = 0;    % Useful with hideName if the subject ID field in the image header also contains the name:  1(yes) 0(no)
% End of iBT.what.disp.do section


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 3: defaults
%
% Assumptions/options in the stages...
% bits you probably don't need to change
% (some settings here may not actually be used
%  if the relevant flag above has not been set)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%  Display
	iBT.what.disp.show.name = 1;
	iBT.what.disp.show.ID = 1;
	iBT.what.disp.show.date = 1;
	iBT.what.disp.show.voxelSize=1; % 1(yes, default) 0(no)
	iBT.what.disp.show.task = 0;
	iBT.what.disp.show.mrej = 0; % Display effective number of task and rest scans included after motion rejection regressors are taken into account. Requires SPM.mat.
	iBT.what.disp.show.conName = 1;
	% iBT.what.disp.fontsize1 = 13;
	% iBT.what.disp.fontsize2 = 11;
	iBT.what.disp.show.thresh = 1;
	iBT.what.disp.show.warp = 1; 
	iBT.what.disp.show.smooth =1;
	iBT.what.disp.show.colourbar=1;
	iBT.what.disp.transparency = 0;  % Force a fixed transparency (range from 0=default(opaque), 1 = invisible).
	                             % The default is a value dependent on the threshold range such that very low 
				     % threshold images appear opaque)
	iBT.what.disp.ROI.colour = [0.19 0.0 0.38]; % RGB colour of ROI, a triplet of values between 0 and 1; e.g. [0.19 0 0.38] is purple.
	iBT.what.disp.ROI.transparency = 0.1; % transparency of ROI
	iBT.what.disp.threshold.write_t_value_file = 1; % Create a file indicating t for requested p in iBT.what.disp.threshold.thresh (can be used by some iBrain functions)
	iBT.what.disp.threshold.structural.low = 0; % Optional parameter to limit the lowest allowed adaptive value of the grey range (e.g. set to zero to ignore negative values)
	% iBT.what.disp.threshold.structural.high = 10000; % Optional parameter to limit the highest adaptive value of the grey range for structural image display, potentially
                                                        % useful if image is contaminated by outlier high-intensity voxels.
	% iBT.what.disp.threshold.structural.min = 0; % Optional parameter to force the low value of the grey range for structural image display
	% iBT.what.disp.threshold.structural.max = 10000; % Optional parameter to force the high value of the grey range for structural image display
