% Integrated Brain Analysis Toolbox for SPM: 'runinfo_normLegacy_template.m'
% Template version date: 2025-12-30
%
% Template of a file to indicate what you want done:
% This version is suitable for "own-space" input data  
% that has not yet been pre-processed, that you want to
% spatially normalise using SPM's legacy spatial normalisation
% routines - i.e. those utilised by default in SPM8. This
% does not require or utilise a subject's anatomical image, 
% which can be a good choice if a structural image is
% not available, or if the functional images suffer
% from substantial uncorrectable distortion that can lead to
% inacurate cross-modal registration. 
% Please copy and edit this template to suit your needs.
%
% 
% To execute this script, either select run from the iBT 
% menu or type ibt directly at the Matlab command line; you will
% then be prompted to select a runinfo file to execute.
%
% Do not use - or . in the filename of this file, otherwise Matlab
% will have trouble finding it.
%
% Only the iBT structure is actually passed to other scripts;
% all other variables & code here are for convenience
% to set up iBT.

%_______________________________________________________________________________
% Copyright (C) 2004-2025 The Florey Institute of Neuroscience and Mental Health
% David Abbott
%
% This file is part of iBT (the Integrated Brain Analysis Toolbox for SPM).
% See README_iBT.txt for more information.
%
% iBT is free software: you can redistribute it and/or modify it under the
% terms of the GNU General Public License as published by the Free Software
% Foundation, either version 3 of the License, or (at your option) any later
% version.
%_______________________________________________________________________________
%

clear onsets durations tasks % To avoid potential scalar/cell type interference from previous jobs

spm('defaults','fmri');
iBT.what.SpmVersion = spm('Ver');

% Use appropriate version of SPM template extension
switch(iBT.what.SpmVersion),
	case 'SPM2'
        	template_ext = '.mnc';
                stats_ext = '.img';
        case {'SPM5','SPM8'}
                template_ext = '.nii';
                stats_ext = '.img';
        otherwise
                template_ext = '.nii';
                stats_ext = '.nii';
end

iBT.what.SPM.ext = stats_ext; % Used for images generated by SPM
iBT.what.FSL.ext = stats_ext; % Used for images generated by MELODIC
iBT.what.iB.ext = '.img';     % Used for images generated by iBrain

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 1: data/subject info: the WHO
%
% location of data, analysis directories, etc.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% The following can help avoid accidentally running this script in an unintended SPM version:
iBT.what.prefer.SPM = 'SPM12'; % Preferred SPM version for this script (e.g. 'SPM12b'; warns if not exact match). '' or comment out for no preference.

% (usually put the scripts in the analysis working directory, and analysis results will be saved in subdirectories thereunder)
iBT.what.where.awd = pwd ; % Analysis working directory: pwd (without quotes) uses the current directory. 
			   % Otherwise specify an explicit path with a string in quotes, e.g. '/home/username/analysis'

% The following are options to describe how the regressors for each subject will be specified later on:
iBT.what.stats.events.source = 'runinfo'; % OPTIONS: 'none' = No events (often the choice for a functional connectivity study); 
	% 'runinfo' = Event onsets and durations (and heights if applicable) specified directly in this runinfo; 
	% 'textfile' = Read from the text file(s) specified in iBT.who.sub{sub}.sess{ses}.[onset|dur|height]_files; 
	% 'runinfo & textfile' = both of the above;
	% Specifying heights is optional. If modulating heights are provided (one value for each event onset), 
        %   these are multiplied by the event structure and convolved with the HRF.  

iBT.what.stats.onset_dur_units = 'scans';     % OPTIONS: 'scans'|'secs' = units for onsets & durations

% The values of onsets and durations below are used only if iBT.what.stats.events.source contains 'runinfo':
onsets = [0 20 40 60];      % task onsets (one task type, the remainder is REST), 0 is start of first included scan in pick list
durations = [10 10 10 10];  % task duration(s)
heights = []; % Leave empty unless want parametric height regressors 

% onsets{1} = [0 40 80]   % task1 onsets - here we have two task types so split into cells (see below)
% durations{1} = [10 10 10];      % task1 duration(s) 
% task{1} = 'task1'; 	  % 
% onsets{2} = [20 60 100] % 
% durations{2} = [10 10 10];      % task2 duration(s) 
% task{2} = 'task2'; 	  % 
% You might prefer to set tasks names directly in the iBT.who section below if differ amongst sessions,
% but make sure you include cells for each different task if there are several task types. 

% Can also specify filename(s) (wildcards supported) to one or more files from which to load onsets
% and durations  These are ignored unless iBT.what.stats.events.source contains 'textfile'.
% Labels derived from these filenames consist of all except the last four
% characters of the basename (e.g. the column in the design matrix corresponding 
% to "event1_ons.txt" would labelled "event1"). Labels so derived are sorted
% alphabetically to determine their order in the design matrix. A check is made to 
% ensure the sorted array of onset labels matches the sorted array of duration labels.
onset_files    = '*_ons.txt';
duration_files = '*_dur.txt';
height_files   = '*_amp.txt'; % optional event height (amplitude) files

iBT.what.stats.offsets = [0];  % Offset the task onsets creating a separate analysis for each value (units are same as onsets)
%iBT.what.stats.offsets = [0 -6]; % (e.g. [-4 -2 0] would give three sets of analysis; [0] equals no offsets)
                   % Offsets that push the onsets below or above the selected scan range result in that particular onset
                   % being ignored

% Note: iBrainWithinBrain mask is created in pre-processing step (iBrainWithinBrainMask.create)
%       and can subsequently used in statistical analysis as an explicit mask
% Whilst single spaces in iBT.who.sub.sess.rawloc pathnames are supported, please do NOT use spaces in
% processed pathnames.

% You can either set up specific study details here, or by reference to another file.
% Choose by uncommenting one only of the following lines:
%studylistfile='studylist.txt'; % non-blank string indicates read in details from file.
studylistfile=''; % Blank string indicates setup within current runinfo file only


if strcmp(studylistfile,'') == 1 % Set up all details here if we're not reading a study-list file

sub=1;
ses=1;
iBT.who.sub{sub}.ID = ['TEST']; % Subject ID - Analysis subdirectory and contrast names will use this
iBT.who.sub{sub}.sess{ses}.name='OLR';  %summary name for this task (independent of contrasts); if using fMRIPrep, be consistant here
iBT.who.sub{sub}.MasterSession=1; % Initial intra-subject inter-session spatial norm target session number; Ignored if iBT.what.pre.norm.intra.do (below) is 0 
iBT.who.sub{sub}.sess{ses}.rawloc=['/data/sub-55555/func']; % Location of non-preprocessed images
iBT.who.sub{sub}.sess{ses}.loc=fullfile(pwd,['prepro_' iBT.who.sub{sub}.sess{ses}.name]);% Location to put iBT pre-processed data. 
% You can code this, for example, to dynamically embed SPM version and use platform-independent file separators as follows:
% iBT.who.sub{sub}.sess{ses}.loc=fullfile(filesep, 'data', 'user', 'data', [iBT.what.SpmVersion '_preprocessed'],'subject_name');% Location of pre-processed data
iBT.who.sub{sub}.sess{ses}.disp.loc=fullfile(iBT.what.where.awd, 'RFX',  iBT.who.sub{sub}.ID); % Used only if iBT.what.disp.OTHER.do > 0. See note below.
iBT.who.sub{sub}.sess{ses}.MELODIC.loc=['/data/user/data/ica/subject.ica'];% MELODIC ICA directory (if ICA performed)
iBT.who.sub{sub}.sess{ses}.swi=0; % full path of source weighted image for lesion masking, 0= don't use (the swi should be 0 in the lesion, 1 elsewhere)
iBT.who.sub{sub}.sess{ses}.ImageSWIdrawnUpon=0; % Full path of image from which the source weighted image was derived; this is only
	% required for coregistration if the swi is not in the space of the current pre-processed mean.0 = none or swi already in same space.
iBT.who.sub{sub}.sess{ses}.tscans=-1; %total number of scans in the data directory, -1= autodetect
iBT.who.sub{sub}.sess{ses}.nscans=80; %number of scans to include in analysis, -1= autodetect
iBT.who.sub{sub}.sess{ses}.pick=[11:90];  %range of scans to include in analysis (ignored for pre-processing; first image is 1)
iBT.who.sub{sub}.sess{ses}.denoised_pick_adjustment=[0 0];  % Adjustment if you have denoised only a subset of the original
	% preprocessed images. Set to [a b] where a = number of image volumes removed from the start of the session
	% and b = number of volumes removed from the end of the session. This is used to adjust the pick list
	% when selecting denoised images (but not when extracting realignment parameters because the original
	% realignment parameter file is used, for which the original pick list is appropriate).
iBT.who.sub{sub}.sess{ses}.task=iBT.who.sub{sub}.sess{ses}.name;  %name(s) for the particular task(s)
%iBT.who.sub{sub}.sess{ses}.TR=0.9; % TR in seconds. Ignored unless iBT.what.pre.header_info is set to 2 in iBT.what.pre section below.
iBT.who.sub{sub}.sess{ses}.onsets=onsets; % Ignored unless iBT.what.stats.events.source (set above) contains 'runinfo' 
iBT.who.sub{sub}.sess{ses}.dur=durations; % Ignored unless iBT.what.stats.events.source (set above) contains 'runinfo'
% iBT.who.sub{sub}.sess{ses}.heights=heights; % Optional parameter: Event heights
iBT.who.sub{sub}.sess{ses}.onset_files=onset_files;  % Ignored unless iBT.what.stats.events.source (set above) includes 'textfile'
iBT.who.sub{sub}.sess{ses}.dur_files=duration_files; % Ignored unless iBT.what.stats.events.source (set above) includes 'textfile'
% iBT.who.sub{sub}.sess{ses}.height_files=height_files; % Optional parameter: Wildcard of file(s) containing event heights
iBT.who.sub{sub}.sess{ses}.iBrainWithinBrainMask.create = 0.1;  % threshold (e.g. 0.3) for iBrainWithinBrain mask
iBT.who.sub{sub}.sess{ses}.BETwithinBrainMask.create = '-m -R -f 0.4'; % Switches to create within-brain mask with BET. Ignored if iBT.what.pre.Create_n_BETwithinBrainMask = 0;
iBT.who.sub{sub}.sess{ses}.ROI_loc = iBT.what.where.awd; % Where to look for confound and ROI files. e.g. iBT.who.sub{sub}.sess{ses}.loc
iBT.who.sub{sub}.sess{ses}.Confounds_files = ['c_' iBT.who.sub{sub}.ID '_*.dat']; % ignored if iBT.what.stats.Confounds_timecourse.do = 0;
iBT.who.sub{sub}.sess{ses}.Confounds_mask = 'c_mask_fc_*.img'; % ignored if iBT.what.stats.Confounds_mask_timecourse.do = 0
%iBT.who.sub{sub}.sess{ses}.Confounds_fmriprep = { 'csf' 'white_matter' }; % ignored if iBT.what.stats.Confounds_fmriprep.do = 0; List 
   %column headings of any timeseries you want to include (except the primary 6 motion confounds, handled by iBT.what.stats.mc.fmriprep)
iBT.who.sub{sub}.sess{ses}.fmriprep.wild = ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '_desc-confounds_?????????s.tsv'];
iBT.who.sub{sub}.sess{ses}.Regressor_files = ['i_' iBT.who.sub{sub}.ID '_*.dat']; % regressors of interest; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.timecourse.do = 0;
iBT.who.sub{sub}.sess{ses}.ROI_mask = 'i_mask_fc_*.img'; % regressors of interest; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.ROI_mask_timecourse.do = 0
iBT.who.sub{sub}.sess{ses}.ROI_coord = [0,0,0];   % in units of ROI_coord_units (see below); ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.voxel.do = 0 
iBT.who.sub{sub}.sess{ses}.ROI_coord_units = 'voxels';   % 'mm' or 'voxels' 
iBT.who.sub{sub}.sess{ses}.ROI_radius = 5; % in mm; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.voxel.do = 0 

% Session specific wildcards: The following session-specific filename wildcards
% are useful if data from several sessions has been saved into a single folder.
% This can happen, for example, if data is pre-processed by another tool such
% as fMRIPrep. Alternative global wildcards appear later in the runinfo 
% (e.g. iBT.what.pre.wild.raw, iBT.what.stats.r_wild, etc.). 
% Note that any session-specific wildcards uncommented here will take
% precedence over their global counterparts:
%iBT.who.sub{sub}.sess{ses}.wild.input = ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '*.dcm']; % wildcard for input images (e.g. DICOM)
%iBT.who.sub{sub}.sess{ses}.wild.raw =   ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '_space-MNI152NLin6Asym_res-2_desc-preproc_bold????.nii']; % wildcard for NIfTI fMRI images
%iBT.who.sub{sub}.sess{ses}.wild.r_ExplicitMask = [''];
%iBT.who.sub{sub}.sess{ses}.wild.n_ExplicitMask = ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '_space-MNI152NLin6Asym_res-2_desc-brain_mask????.nii']; % wildcard for NIfTI fMRI within-brain mask  
%iBT.who.sub{sub}.sess{ses}.wild.slice =   iBT.who.sub{sub}.sess{ses}.wild.raw; % Because fMRIPrep has already done the slice timing adjustment
%iBT.who.sub{sub}.sess{ses}.wild.realign = iBT.who.sub{sub}.sess{ses}.wild.raw; % Because fMRIPrep has already done the realignment
%iBT.who.sub{sub}.sess{ses}.wild.r = cat(2, 's', iBT.who.sub{sub}.sess{ses}.wild.raw);	% wildcard for non-normalised images to analyse
%iBT.who.sub{sub}.sess{ses}.wild.n = cat(2, 's', iBT.who.sub{sub}.sess{ses}.wild.raw);	% wildcard for spatially-normalised images to analyse
%iBT.who.sub{sub}.sess{ses}.wild.denoised_r = cat(2, 'ds', iBT.who.sub{sub}.sess{ses}.wild.raw);
%iBT.who.sub{sub}.sess{ses}.wild.denoised_n = cat(2, 'ds', iBT.who.sub{sub}.sess{ses}.wild.raw);

% sub = sub + 1; ses = 1;
% or
% ses = ses + 1;
% You can specify the next subject and/or session using similar variables 
% to those for first. Just makes sure sub and ses are set to the next
% session or subject and copy and paste the iBT.who.sub{sub}.sess{ses}
% variables above to a new sub and ses below

% Note on iBT.who.sub{sub}.sess{ses}.disp.loc: This can be used to facilitate
% automated display of one or more random effects (RFX) or other arbitrary
% analyses (see also iBT.what.disp.OTHER.do )
% Presently the toolbox does not perform 2nd level statistical analyses 
% automatically, but it can assist with display of the results of a 
% manually-generated 2nd level analysis. It is best to make a separate 
% runinfo for this purpose: You can use the {sub} index to loop through 
% the locations of different group analyses (for example, we've used this
% to generate summary images of several group random effects analyses that
% were conducted for different seed voxel locations in a series of 
% functional connectivity analyses). Optionally, to have informatively labeled
% display pages, you can have a _header_info.txt file in each folder, or specify
% the pre-processed directory of just one of the subjects within each group 
% in iBT.who.sub{sub}.sess{ses}.loc; the display routine will then read 
% image information such as TR and voxel size from that subject (assuming
% that is the same for all subjects in the group).




else %  studylistfile is not empty, so read multiple study details in from that file instead
% The file must contain one line per session with the following seven or more space-separated 
% fields in the order shown:
% subID master_flag rawloc loc task pick_start pick_end [ROIx ROIy ROIz] [SOCK_wildcard]
% Comment lines beginning with a # are permitted, as are filenames with spaces if quoted.
%
% You might want to change in the 'for loop' below the
% values of ROI_radius and/or iBrainWithinBrainMask.create 
% on the last couple of lines (and the TR if you are specifying
% this manually). Otherwise you probably don't
% need to change the code below unless you want to
% customise the format of the studylistfile (which you may need
% to do if any presently fixed fields are not constant across 
% sessions).

 f = fopen(studylistfile);             
   s = textscan(f,'%s','delimiter','\r\n','CommentStyle', '#'); % Read the whole file into variable s, with each line a separate cell, ignoring comments
 fclose(f);
 s = cellstr(s{1});
 num_rows = size(s,1);

 IDcol=1;masterCol=2;rawCol=3;locCol=4;taskCol=5;pickStartCol=6;pickEndCol=7;xCol=8;yCol=9;zCol=10;
 sub=0; %We increment on first pass through loop, so will count from 1.
 last_ID='';
 x=0;y=0;z=0; % initialise in case not present.
 for i=1:num_rows,
   if size(s{i},1) > 0
     studyLine=textscan(s{i},'%q','CommentStyle', '#'); % Read text of each line into separate fields (supports quoting of delimiter characters)
     studyLine=studyLine{1};
   else studyLine=''; end;
   num_cols=size(studyLine,1);
   if num_cols >= 7,
     ID = studyLine{IDcol};
     if strcmp(ID,last_ID)==0 
   	sub = sub + 1; last_ID = ID; ses=1; 
	iBT.who.sub{sub}.MasterSession=1; % Ensure a session is designated master even if not specified. If specified this will be changed below.
     else
   	ses = ses+1;
     end
     rawloc = studyLine{rawCol};
     loc = studyLine{locCol};
     task = studyLine{taskCol};
     frames = [str2num(studyLine{pickStartCol}) : str2num(studyLine{pickEndCol})];
     master_flag =str2num(studyLine{masterCol});
     if num_cols >= 10,
       x = str2num(studyLine{xCol});
       y = str2num(studyLine{yCol});
       z = str2num(studyLine{zCol});
     end %if num_cols >= 10
   
     iBT.who.sub{sub}.ID = ID;
     if master_flag == 1,
   	iBT.who.sub{sub}.MasterSession=ses;  % Initial intra-subject inter-session spatial norm target session number; Ignored if iBT.what.pre.norm.intra.do (below) is 0 
     end
     iBT.who.sub{sub}.sess{ses}.rawloc = rawloc;
     iBT.who.sub{sub}.sess{ses}.loc = loc;
     % iBT.who.sub{sub}.sess{ses}.disp.loc = rawloc; % Used only if iBT.what.disp.OTHER.do > 0. See note below.
     iBT.who.sub{sub}.sess{ses}.tscans = -1; %total number of scans in the data directory, -1= autodetect
     iBT.who.sub{sub}.sess{ses}.nscans = length(frames); %number of scans to include in analysis, -1= autodetect
     iBT.who.sub{sub}.sess{ses}.pick = frames;  %range of scans to include in analysis
	 iBT.who.sub{sub}.sess{ses}.name = task; %single string summary name for this task (independent of contrasts); if using fMRIPrep, be consistant here
	 iBT.who.sub{sub}.sess{ses}.task = task;  %name(s) for the particular task(s)
     %iBT.who.sub{sub}.sess{ses}.TR=0.9; % TR in seconds. Ignored unless iBT.what.pre.header_info is set to 2 in iBT.what.pre section below.
     iBT.who.sub{sub}.sess{ses}.onsets=onsets; % Ignored unless iBT.what.stats.events.source (set above) contains 'runinfo' 
     iBT.who.sub{sub}.sess{ses}.dur=durations; % Ignored unless iBT.what.stats.events.source (set above) contains 'runinfo'
     iBT.who.sub{sub}.sess{ses}.heights=heights; % Optional parameter: Event heights
     iBT.who.sub{sub}.sess{ses}.onset_files=onset_files;  % Ignored unless iBT.what.stats.events.source (set above) includes 'textfile'
     iBT.who.sub{sub}.sess{ses}.dur_files=duration_files; % Ignored unless iBT.what.stats.events.source (set above) includes 'textfile'
     iBT.who.sub{sub}.sess{ses}.height_files=height_files;% Optional parameter: Wildcard of file(s) containing event heights
     iBT.who.sub{sub}.sess{ses}.Confounds_files = ['c_' iBT.who.sub{sub}.ID '_*.dat']; % ignored if iBT.what.stats.Confounds_timecourse.do = 0;
     iBT.who.sub{sub}.sess{ses}.Confounds_mask = 'c_mask_fc_*.img'; % ignored if iBT.what.stats.Confounds_mask_timecourse.do = 0
     % iBT.who.sub{sub}.sess{ses}.Confounds_fmriprep = { 'csf' 'white_matter' }; % List column headings of any you want to include, except the primary 6 motion confounds which are dealt with elsewhere; ignored if iBT.what.stats.Confounds_fmriprep.do = 0;
     iBT.who.sub{sub}.sess{ses}.Regressor_files = ['i_' iBT.who.sub{sub}.ID '_*.dat']; % regressors of interest; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.timecourse.do = 0;
     iBT.who.sub{sub}.sess{ses}.ROI_mask = 'i_mask_fc_*.img'; % regressors of interest; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.ROI_mask_timecourse.do = 0
     iBT.who.sub{sub}.sess{ses}.ROI_coord = [x,y,z];  % in units of ROI_coord_units (see below); ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.voxel.do = 0 
     iBT.who.sub{sub}.sess{ses}.ROI_coord_units = 'voxels';   % 'mm' or 'voxels' 
     iBT.who.sub{sub}.sess{ses}.ROI_radius = 5; % in mm; ignored if iBT.what.stats.fc.do = 0 or iBT.what.stats.fc.voxel.do = 0 
     iBT.who.sub{sub}.sess{ses}.iBrainWithinBrainMask.create = 0.3;  % threshold (e.g. 0.3) for iBrainWithinBrain mask
     iBT.who.sub{sub}.sess{ses}.BETwithinBrainMask.create = '-m -R -f 0.4'; % Switches to create within-brain mask with BET. Ignored if iBT.what.pre.Create_n_BETwithinBrainMask = 0;
     iBT.who.sub{sub}.sess{ses}.TR=0; % TR in seconds. Ignored unless iBT.what.pre.header_info is set to 2 in  iBT.what.pre section below.
	 % Session specific wildcards - see earlier note:
	%iBT.who.sub{sub}.sess{ses}.wild.input = ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '*.dcm']; % wildcard for input images (e.g. DICOM)
	%iBT.who.sub{sub}.sess{ses}.wild.raw =   ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '_space-MNI152NLin6Asym_res-2_desc-preproc_bold????.nii']; % wildcard for NIfTI fMRI images
	%iBT.who.sub{sub}.sess{ses}.wild.r_ExplicitMask = [''];
	%iBT.who.sub{sub}.sess{ses}.wild.n_ExplicitMask = ['sub-*_task-' iBT.who.sub{sub}.sess{ses}.name '_space-MNI152NLin6Asym_res-2_desc-brain_mask????.nii']; % wildcard for NIfTI fMRI within-brain mask  
	%iBT.who.sub{sub}.sess{ses}.wild.slice =   iBT.who.sub{sub}.sess{ses}.wild.raw; % Because fMRIPrep has already done the slice timing adjustment
	%iBT.who.sub{sub}.sess{ses}.wild.realign = iBT.who.sub{sub}.sess{ses}.wild.raw; % Because fMRIPrep has already done the realignment
	%iBT.who.sub{sub}.sess{ses}.wild.r = cat(2, 's', iBT.who.sub{sub}.sess{ses}.wild.raw);	% wildcard for non-normalised images to analyse
	%iBT.who.sub{sub}.sess{ses}.wild.n = cat(2, 's', iBT.who.sub{sub}.sess{ses}.wild.raw);	% wildcard for spatially-normalised images to analyse
	%iBT.who.sub{sub}.sess{ses}.wild.denoised_r = cat(2, 'ds', iBT.who.sub{sub}.sess{ses}.wild.raw);
	%iBT.who.sub{sub}.sess{ses}.wild.denoised_n = cat(2, 'ds', iBT.who.sub{sub}.sess{ses}.wild.raw);

     disp(sprintf('Successfully loaded instructions for subject %i, session %i. ',sub,ses));
   elseif num_cols > 0 
     error(sprintf('Error: line %i of studylist file %s has only %i fields (expected at least 7).',i,studylistfile,num_cols));
   end %if num_cols >= 7 elseif num_cols > 0
 end % for
 pause(2); % Give the user a couple of seconds to see how many subjects and sessions we found in the studylist.
end % if read_study_list_file


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 2: input choices
%
% specify WHAT you want to do
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Note that as listed below, most pre-processing items depend on all previous items
% having been completed. Exceptions are:
%   * iBrainConvert and DICOMconvert work together to determine which conversion to perform
%   * WriteRealign and SmoothRealign can be omitted if you don't want to do
%     individual-space analysis.
%   * SpatialNorm can be omitted if you don't want to do group analysis.
%
iBT.what.pre.do=1;                 % preprocess data: 1(yes) 0(no)
   iBT.what.pre.fmriprep.done=0;  % Has the "raw" data been processed with fmriprep?: 1(yes) 0(no)
   iBT.what.pre.iBrainServer = 10;  % If iBrain is required, use server mode?  0 = No, 1= yes, or 
	% >1= yes and attempt to start a new iBrain server process if the job is not accepted 
	% after this many seconds (requires iBrain command to be in the default path). Recommended value is 10.
	% If >0, then iBrain commands are sent to a running iBrain Server process to be executed.
	% If 0, then iBrain commands are run in separate processes initiated from the
	%	command line, requiring an IDL licence to avoid repeated IDL click-to-continue
	%	splash screens; also need an iBrainr command script in path to run the job.
   iBT.what.pre.iBrainConvert = 0; % convert data to Analyze format using iBrain: 1(yes) 0(no) -1(already done)
   			       %  (assumes GE input format unless DICOMconvert = 1 (see below) )
   iBT.what.pre.DICOMconvert = 2;  % 0, 1 or 2 (or negative if already done).
    % Set non-zero if input data is in DICOM format. DICOM conversion will then be performed using iBrain if iBrainConvert = 1, 
	% otherwise it will use SPM routines, in which case if set to 2 (and if using SPM12 r7201 or later), the SPM converter
	% will also write out JSON files.
   iBT.what.pre.FSLsplit = iBT.what.pre.fmriprep.done; % 0 or 1 or -1(already done). Input data is already in a format FSL's 
   	% fslsplit recognises - use fslsplit to copy/convert to 3D uncompressed NIfTI files for maximum SPM & iBT compatibility
   iBT.what.pre.header_info = 3;% Create a _header_info.txt file in the pre-processed data folder containing relevant 
	   % information about the original images. This file is read by the pre-processing, stats
	   % and display modules of iBT.
	   %  1: yes, use iBrain to extract information such as TR from an original scanner image
	   % -1: already done 1 (but attempt to re-create it if the file no longer exists)
	   %  2: yes, limited to specifying the TR manually via iBT.who.sub{sub}.sess{ses}.TR
	   %     Note that specifying TR manually is not recommended as it is subject to human error.
	   % -2: already done 2 (but attempt to re-create it if the file no longer exists)
	   %  3: yes, read the TR from a JSON sidecar file (best for recent SPM and BIDS, including fMRIPrep)
	   % -3: already done 3 (but attempt to re-create it if the file no longer exists)
	   %  4: yes, read the TR from NIfTI header (may work for some conversions e.g. dcm2niix)
	   % -4: already done 4 (but attempt to re-create it if the file no longer exists)
	   %  0: No, don't create the _header_info.txt file.
   iBT.what.pre.hideName = 0;	% When writing _header_info.txt, insert iBT.who.sub.ID rather than the name obtained from the image header: 1(yes) 0(no)
   iBT.what.pre.hideID = 0; % Implies hideName above but also suppress the subject ID field:  1(yes) 0(no)
   iBT.what.pre.SliceTiming = 1;   % 1(yes) 0(no) -1(already done)
   iBT.what.pre.iBrainRealignTarget = 0; % Use iBrain to select the optimum target for realignment? 1(yes) 0(no) -1(already done)
   iBT.what.pre.Realign = 1;       % motion correction: 1(yes, full 3D), 2(yes, x & y shifts & rotation about z axis only), 0(no), -1(already done by iBT or fmriprep)
   iBT.what.pre.WriteRealign = 1;  % write images for own-space analysis: 1(yes) 0(no) -1(already done)
   iBT.what.pre.mean = 1; % Still write a mean functional image even image if iBT.what.pre.Realign <= 0: 1(yes) 0(no) -1(already done)
   iBT.what.pre.Create_r_iBrainWithinBrainMask = 0;  % Create iBrainMask_r*.img for realigned non-norm images: 1(yes) 0(no) -1(already done)
   iBT.what.pre.Create_r_BETwithinBrainMask = 0;  % Create BETmask_r*.img for realigned non-norm images:
		% 0(no), -1 (already done). Requires FSL. See http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET
   iBT.what.pre.SmoothRealign = 1; % smooth images for own-space analysis: 1(yes) 0(no) -1(already done)
     iBT.what.pre.r_smooth_fwhm = 6;	% Scalar or [3 element array] smoothing kernel(mm) for realigned (non-normalised) (ignored if iBT.what.pre.SmoothRealign false)
   % Set following to 0 if want to omit the spatial normalisation to template & smooth steps:
   iBT.what.pre.norm.do = 1;   % perform spatial normalisation to a template: 0(no), 1(yes, nonlinear warp), 2(yes, affine only), 3(yes, near rigid-body only), -1 or -2 or -3 (already done)
    % Spatial normalisation options (ignored unless iBT.what.pre.norm.do  > 0 - i.e. not 0 or already done):
     iBT.what.pre.norm.intra.do = 0;  % each patient was scanned more than once and within patient spatial normalisation 
		% is also required : 0(no), 1(yes, nonlinear warp), 2(yes, affine only), -1 or -2 (already done)
     iBT.what.pre.norm.intra.do_swi = 1;  % 1(yes) 0(no). If iBT.who.sub{sub}.sess{}.swi is set (lesion mask), also apply the swi during the
     		% intra-normalisation. You may want to do this if the lesion changes (e.g. pre and post surgery sessions). 
		% If the lesion is not expected to change, then it is probably best to set this option to 0 so that
		% the lesion is included in the intra-session normalisation cost function.
     iBT.what.pre.norm.BiasCorrect = 0; % Additional explicit Bias correction prior to spatial normalisation: 1(yes) 0(no) (Requires SPM8 or later)
     iBT.what.pre.norm.temp=['EPI' template_ext];% standard template EPI image supplied with SPM (ignored if SpatialNorm is 0)
     iBT.what.pre.norm.tempLabel=['SPM MNI-space EPI template'];% Optional label to use for the template when describing it in the results display
     %iBT.what.pre.norm.temp='bri-e29-s8mm.img';% template EPI image (BRI 3T)
     iBT.what.pre.norm.WriteNorm = 1; % write smoothed images for spatial normalisation (ignored if SpatialNorm is 0): 1(yes) 0(no) -1(already done)
       iBT.what.pre.n_smooth_fwhm = 6;  % Scalar or [3 element array] smoothing kernel(mm) for spatially normalised images
    % end of spatial normalisation options:

   iBT.what.pre.Create_n_iBrainWithinBrainMask = 0;  % Create iBrainMask_n*.img for spatially normalised images:
   		% 1(yes), 2(yes, plus improve with MILXView; works on GNU+Linux only and only if you have MILXView installed) 
		% 0(no), -1 or -2 (already done)
   iBT.what.pre.Create_n_BETwithinBrainMask = 0;  % Create BETmask_n*.img for spatially normalised images:
		% 0(no), -1 (already done). Requires FSL. See http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET
   % Note: You can elect to create both masks here if you wish (i.e. iBrain and BET). The one actually used during statistical 
   %       processing is determined by the *_withinBrainMask values set in the stats section below. If you elect
   %       not to create a WithinBrainMask (i.e. both options 0 above) then you will need to select the SPM mask in
   %       the stats section below.

   iBT.what.pre.Cleanup = 1;       % remove preprocessing temp files (iBT.what.pre.wild.slice and iBT.what.pre.wild.realign): 1(yes) 0(no)
   			       % You can safely do this if you only ever look at the smoothed files.

iBT.what.stats.do=1;     % analyse data: 1(yes) 0(no)
	% Select the type of analysis. Whilst you can do multiple analyses at once (results go to separate 
	% subdirectories), you should be careful. It should be OK to select both subjects and group, but
	% if you also want sessions (i.e. independent single-session analysis) and there exist multiple sessions,
	% then you probably want the realignment target to be current session rather than first session. This
	% would require a different set of pre-processed data to that which you'd want for a multi-session analysis.
	% You can specify 0 to skip, 1 to loop through all, or -N to do the Nth subject or session as indicated.
        iBT.what.stats.sessions.do = 1; % -N,0,1 Analyse each session of each subject independently: (Nth) single-subject, single-session design
        iBT.what.stats.subjects.do = 0; % -N,0,1 Analyse each subject independently: (Nth) single-subject, single or multi-session design
        iBT.what.stats.group.do = 0;    % -N,0,1 Analyse subjects together: multi-subject, (Nth) single session fixed-effects design;
      	 	 	 	    % i.e. set iBT.what.stats.group.do = -3 to do a group analysis of only the 3rd session of each subject.
 		 	 	 	    % Note that fixed effects designs are not usually recommended other than for hypothesis generating pilot studies
        %NOTE: This script does not do a 2nd-level random effects analysis
	%     (although it can be used to display the results).
	%      For such group analyses, we use this script to do the 1st level
	%      of the analysis, and then use SPM without this toolbox to do
	%      the 2nd level statistics. Then we configure another runinfo
	%      just to display the results.
      
	iBT.what.stats.Confounds_timecourse.do = 0; % Use time-courses stored in files: 0(no), 1(yes, text files), 2(yes, mat files with time series in variable Y)
	     % This is usually used with functional connectivity, however it can also be used for other analyses. 
	     % Specify the wildcard for the files via iBT.who.sub{sub}.sess{ses}.Confounds_files
	     % If more than one timecourse is specified, each will occupy a separate column in the design matrix.
	
	iBT.what.stats.Confounds_mask_timecourse.do = 0; % Use an average timecourse of voxels within given region of interest: 1(yes) 0(no)
	     % This is usually used with functional connectivity, however it can also be used for other analyses. 
	     % Specify the wildcard for the ROI image file(s) via iBT.who.sub{sub}.sess{ses}.Confounds_mask
	     % If more than one confound ROI image is specified, each will occupy a separate column in the design matrix.

	iBT.what.stats.Confounds_fmriprep.do = 0; % Use time-courses stored in the fmriprep timeseries file: 0(no), 1(yes)
	     % This is usually used with functional connectivity, however it can also be used for other analyses. 
	     % If this option is enabled it is assumed the motion correction file is an fmriprep file
	     % If more than one timecourse is specified, each will occupy a separate column in the design matrix.
	     
	iBT.what.stats.fc.do = 0; % perform functional connectivity analysis; 1(yes) 0(no)
	  % Specify type of seeds (multiple types are allowed):
 	   iBT.what.stats.fc.timecourse.do = 0; % Use pre-calculated time-courses stored in files: 0(no), 1(yes, text files), 2(yes, mat files with time series in variable Y)
	     % Specify the wildcard for the files via iBT.who.sub{sub}.sess{ses}.Regressor_files
	     % If more than one timecourse is specified, each will occupy a separate column in the design matrix.
	   iBT.what.stats.fc.ROI_mask_timecourse.do = 0; % Use an average timecourse of voxels within given region of interest: 1(yes) 0(no)
	     % Specify the wildcard for the ROI image file(s) via iBT.who.sub{sub}.sess{ses}.ROI_mask
	     % If more than one ROI image is specified, each will occupy a separate column in the design matrix.
	   iBT.what.stats.fc.voxel.do = 0 ; % Use a voxel co-ordinate: 1(yes) 0(no)
	     % Specify the co-ordinate and radius in iBT.who.sub{sub}.sess{ses}.ROI_coord and iBT.who.sub{sub}.sess{ses}.ROI_radius

	iBT.what.stats.own_space.do = 0;   % Analyse subject's own-space data 
       				       % Note: Group analyses are not performed on own-space data even if iBT.what.stats.group.do is set    
	    iBT.what.stats.r_withinBrainMask = 'SPM'; % Set this to 'iBrain' or 'BET' or 'SPM' or 'Explicit' depending upon type of own-space mask you want to use.
		                                             % The 'Explicit' option will use the file matching the wildcard specified in iBT.who.sub{sub}.sess{ses}.wild.r_ExplicitMask

	iBT.what.stats.norm_space.do = 1;  % Analyse subjects' spatially normalised data
	    iBT.what.stats.n_withinBrainMask = 'SPM'; % Set this to 'iBrain' or 'BET' or 'SPM' or 'Explicit' depending upon type of norm-space mask you want to use.
		                                             % The 'Explicit' option will use the file matching the wildcard specified in iBT.who.sub{sub}.sess{ses}.wild.n_ExplicitMask

	iBT.what.stats.denoised.do = 0;  % Analyse subjects' SOCK de-noised data (see also iBT.what.stats.denoised.folder and iBT.what.stats.denoised.n_wild);  1(yes) 0(no)

	iBT.what.stats.denoised.SOCK.adjust_erdf = 0; % Reduce estimated effective degrees of freedom by number of SOCK regressors used in denoising: 1(yes) 0(no) -1(already done)
						
	iBT.what.stats.denoised.adjust_erdf = 0; % <=0: Add this (negative) number to estimated effective degrees of freedom: 
		% typically used to manually reduce by number of regressors used in denoising undertaken by an external routine
		% that iBT does not otherwise directly support. See also iBT.what.stats.denoised.SOCK.adjust_erdf
	
	iBT.what.stats.sessions.which = 0; % Restrict analysis to a particular session (0 = all)
	
	iBT.what.stats.design.configure = 1; % Configure parameters of design matrix: 1(yes) 0(no) -1(already done)

  iBT.what.stats.design.savePreliminaryFig = 0; % Save out figures of the preliminary design matrix (i.e. design matrix that spm produces, which does not include extra orthogonalisation performed by iBT): 0(no) 1(yes) default = no

	iBT.what.stats.estimate = 1; % Estimate parameters of design matrix: 1(yes) 0(no) -1(already done)

        iBT.what.stats.event_con = 1; % Generate separate T contrasts for certain effects of interest
				  % 0=none, 1=primary effects/events only (i.e. not as a result of additional basis functions)
				  % 2=every effect of interest, including events convolved with additional basis functions
				  % negative value = already done. Both positive and negative contrasts are generated for each effect.
 	iBT.what.stats.extra_con.name    = {}; % e.g. { 'Early - Late'  'Late - Early' }; % Cell array of contrast-of-interest name strings; {} if none.
         iBT.what.stats.extra_con.type   = {}; % e.g. { 'T'             'T'            }; % Cell array of contrast-of-interest type strings; {} if none.
         iBT.what.stats.extra_con.weight = {}; % e.g. { [ 1 0 -1]        [ -1 0  1]    }; % Cell array of contrast-of-interest weight arrays; {} if none.
	% iBT.what.stats.extra_con above is used to generate separate contrasts for certain combinations of effects of 
	% interest (automatically taking into account any confounds). e.g. { [ 1 0 0 -1] [ -1 0 0 1] } would create two contrasts,
	% the first effect4 - effect1, and the second effect1 - effect4, even though these effects may be separated by a large number
	% of other confound columns in the design matrix. Only one positive contrast is generated as specified (no automatic negative version).

	iBT.what.stats.evalCons = 1;  % Evaluate contrasts: 1(yes) 0(no) -1(already done)

	% Note: If iBT.what.stats.design.configure, estimate, and evalCons are all -1, SPM.mat will not be saved or updated.
	%        This can be useful for example if you'd like to investigate scans that would be rejected
	%        for different scan-scan motion thresholds without updating anything in the analysis folder.

	iBT.what.stats.data_link = 1; % Create in the results folder a symbolic link to the pre-processed data folder for convenience (GNU+Linux and MacOSX only)
			% WARNING: Matlab will follow links (as will Windows when accessing a samba file share) so if you
			% allow link creation and then delete your analysis folder from within the Matlab GUI or Windows Explorer
			% then your pre-processed files will also be deleted!

	iBT.what.stats.make_data_links_only	= 0; % Assume all the stats have already been calculated but the
					     %  links were not made originally - make them now 
					     % without re-running stats (don't forget to also set iBT.what.stats.data_link above)
	
% End of iBT.what.stats section

iBT.what.cons.do=0; % Create extra contrasts: 1(yes) 0(no) 
% Note1: Individual effect contrasts are already created in iBT.what.stats above
% Note2: This section is currently limited to single-session designs.

	iBT.what.cons.start=38;	% Number of the first new contrast we are defining. If this
				% does not match the next available contrast number in the SPM.mat file,
				% then an error is printed and nothing is done.
				% (Useful to prevent repeated executions of this script adding the same contrasts)
	iBT.what.cons.n_ev=12;  % number of events (columns) of interest
	iBT.what.cons.n_conf=6; % Number of confounds (events of no interest e.g. motion correction parameters)

	i=1;
	iBT.what.cons.cnam{i} = '+effect(name): task-control';
	iBT.what.cons.contrast{i} = [0 0 1 0 0 0 0 0 0 0 0 -1]; 
	iBT.what.cons.ctyp{i} = 'T';
	i = i + 1;
	iBT.what.cons.cnam{i} = '-effect(name): control-task';
	iBT.what.cons.contrast{i} = [0 0 -1 0 0 0 0 0 0 0 0 1]; 
	iBT.what.cons.ctyp{i} = 'T';			

	iBT.what.cons.analysis = 1;	       % analysis is either a single session (1) or subject analysis (2) or RFX analysis (3)
	iBT.what.cons.stats_type = 'auto'; % Add contrast(s) to normalised (norm) or ownspace (own) analysis, or whatever is set in iBT.what.stats (auto).

% End of iBT.what.cons section

iBT.what.custom_stats.do=0;     % analyse data further with your own custom script (see iBT_custom_stats.m) : 1(yes) 0(no)
 % in addition to setting iBT.what.custom_stats.do = 1 above to enable your script to be called, 
 % you can also create additional iBT.what.custom_stats.* variables here if you want to set
 % information here to pass to your custom script.
	%iBT.what.custom_stats.example = value;
% End of iBT.what.custom_stats section

iBT.what.MELODIC.do=0; % MELODIC ICA analysis?: 1(yes) 0(no) 
%  NOTE: At the time of writing this toolbox does not actually run a MELODIC analysis
%        so the flag above is ignored.
%        You currently need to run MELODIC separately, however the parameters you used should be entered
%        here so the display section can use them to label the analysis appropriately.
% 
	iBT.what.MELODIC.norm_space.do = 1;  % Analyse subjects' spatially normalised data (otherwise own-space assumed)

% End of iBT.what.MELODIC section

iBT.what.li.do=0; % Determine laterality indices: 1(yes) 0(no) (Note: can be overridden by iBT.what.li.own.do & iBT.what.li.norm.do)
	% NOTE: The laterality graphing function makes use of jbtest which requires the Matlab Statistics Toolbox;
	%        to disable use of jbtest, set iBT.what.li.jb_alpha to 0 later in this file.
	iBT.what.li.own.do=0; % Determine laterality indices for own-space analysis: 1(yes) 0(no)
	iBT.what.li.norm.do=iBT.what.li.do; % Determine laterality indices for spatially normalised analysis: 1(yes) 0(no)
	iBT.what.li.wild=['spmT_????' stats_ext]; % Wildcard of the statistic image(s) for which to calculate laterality
		% Be careful to maintain consistency with control data - see also iBT.what.li.control_index_mapping
	iBT.what.li.roi_dir='/data/LI/ROIs/'; % where the left and right ROI images are located
 	iBT.what.li.left_roi='left_cortical_ROI_mask.img';  % filename of the left (or typically dominant) ROI image
	iBT.what.li.right_roi='right_cortical_ROI_mask.img'; % filename of the right (or typically non-dominant) ROI image
	iBT.what.li.save.mat=1; % Write LI data as a mat file: 1(yes) 0(no)
	iBT.what.li.save.text=0; % Write LI data as an Excel readable text file: 1(yes) 0(no)
%	 iBT.what.li.save.path = fullfile(pwd,'li_data'); % Where to save output files. Default if not set is in each individual's spm folder.
	iBT.what.li.reuse_existing = 1; % If set and a previous compatible li_active*.mat file exists, script will read it rather than re-calculating LIs.
	iBT.what.li.do_graph=1; % Plot LI data: 1(yes) 0(no)
	  iBT.what.li.save.graph = 1; % Save the plot(s): 1(yes) 0(no) (requires iBT.what.li.do_graph)
	  iBT.what.li.save.thresh=1; % Write the adaptive minimum valid Nvox t-threshold to a mat file for subsequent 
	  			 % use by batch_maps: 1(yes) 0(no)
	  iBT.what.li.control_dir='/data/LI/group_LIs/li_data_control_group'; % where previously calculated LI mat files are located -  
	  		; % include in plot as controls. Leave this blank if you haven't yet generated the control data.
	  iBT.what.li.control_wild='li_active*.mat'; % wildcard for the previously calculated LI mat files
	  iBT.what.li.conclusion.do=1; % Show conclusion (typical or atypical) prominently on summary plot: 1(yes) 0(no)
	  iBT.what.li.sanity.do=0; % Display the t and LI at the min nVox in the valid control range, and 
	  	% perform a sanity check of the data. The subject may not have performed the correct task if the 
	  	% deactivation appears to be more significant than the activation.  This is assessed by comparing, 
		% between activation and deactivation, the t-value corresponding to the the Nvox threshold at the minimum of the
		% valid group range. This assumes that the first contrast is the activation and the second the deactivation.
%	   iBT.what.li.control_index_mapping=[ 2 1 ]; % Uncomment to change index mapping between previously calculated LI mat files and 
	     ; % current analysis order. e.g. if when calculating the control li mat files the analysis and the iBT.what.li.wild were such that
	     ; % a positive contrast was evaluated first followed by a negative contrast, and the current analysis has the contrasts
	     ; % in the reverse order (or perhaps you just want to evaluate the negative and so set iBT.what.li.wild to just match that) 
	     ; % then you will need to set iBT.what.li.control_index_mapping=[ 2 1 ] so that the current first
	     ; % contrast is compared to the control contrast 2 and the second to control contrast 1. Can also use this to map multiple
	     ; % contrasts to a single control contrast (perhaps you have two sessions of the same thing). e.g [ 1 1 2 1] would compare 
	     ; % each of the first, second and fourth contrasts of the current analysis to the first contrast of the control data, and
	     ; % the third contrast of the current analysis to the second contrast of the control data.
	
% End of iBT.what.li section

iBT.what.disp.do = 1; %Generate summary images: 1(yes) 0(no)
	iBT.what.disp.SPM.do=1;         % Display results of an SPM 1st level analysis
	iBT.what.disp.OTHER.do = 0;	% Display data from a manually generated analysis (need not be from SPM): 0(no) 1(yes) 2(RFX)
					%  (Use iBT.who.sub{sub}.sess{ses}.disp.loc to specify location of the data for each 
					%   analysis - can loop over sub as a surrogate for studies)
	   iBT.what.disp.OTHER.title = 'RFX group analysis'; % Change this to whatever is appropriate.
	iBT.what.disp.MELODIC.do=0;     % Display results of a Melodic ICA analysis
	   iBT.what.disp.MELODIC.wild = 'thresh_zstat*.img';
	   iBT.what.disp.MELODIC.SOCK = 0; % Append SOCK classification to output filenames (and optionally 
	   				% limit display to acceptable categories). 0 (no; display all without labels) or
	   				% 1, 2 or 3 (yes) limiting display up to that category 
	   				% e.g. 2 would display categories 1 & 2 but not 3 (the definite artefact category); 3 displays & labels all.
	   				% (Note: SOCK is an automatic ICA noise classifier available at florey.edu.au/imaging-software ) 
	iBT.what.disp.output_parent_folder = ''; % Set this to something other than '' (e.g. iBT.what.where.awd ) to save the displayed 
		% results in a location separate from the analysis. A folder tree (excluding drive letter if present on 
		% Windows platforms) is then constructed in output_parent_folder that matches the path
		% in which the files would have been saved. For example, if the results would have been 
		% saved in "C:\data\subject2\stats\" and iBT.what.disp.output_parent folder is set to 
		% "D:\display" then results will be saved in  "D:\display\data\subject2\stats\"
	iBT.what.disp.orient.LeftOnRight = 'yes';  % yes = Radiological, no = Neurological orientation display
	iBT.what.disp.orient.AnteriorOnRight = 'no'; % yes = display front towards right of page on sagittal view (default 'no')
	iBT.what.disp.orient.showText = 1; % show text to indicate orientation (assumes RAS +ve): 1(yes, default), 0(no)
	iBT.what.disp.orient.transform = {'axial' 'coronal' 'sagittal'}; % Image orientation for the activation map (axial, coronal, sagittal, tilted)
    iBT.what.disp.orient.slices = {84:-6:-72 78:-6:-108 -78:6:78};  % Slice range corresponding to above orientations (ie. first transform
                         	                                     % uses first slice range, second transform uses second slice range etc
%	iBT.what.disp.orient.slices = {88:-8:-72 72:-8:-96 -64:8:64}; % This is better for 8mm smooth
	% Some other examples:
	% For own-space non-smoothed 64x64x35 with 3.43750 x 3.43752 x 3.4mm voxels:
%        iBT.what.disp.orient.slices = {57.8:-3.4:-57.8 108.280935:-3.437490:-108.280935 -108.28125:3.43750:108.28125 }; % slice range corresponding to original own-space slices
	% This is because when origin not set, SPM8 assumes (32.5,32.5,18) for a 64x64x35 matrix; i.e. ((voxels-1)/2)+1
	% and to minimise display partial voluming, want slice position to be co-incident with a voxel (i.e. integer voxel value)
	% Thus for Z (axial slices) calculate +- range as (35 - 1) slice spacings x 3.4mm / 2 = 57.8.
	% Similarly 63 * 3.43750 / 2 = 108.28125 (X = sagittal)
	% 63 * 3.437490 / 2 = 108.280935 (Y = Coronal)
	%
	% For 44 slices @ 3.0mm, then for Z (axial slices) calculate +- range as (44 - 1) slice spacings x 3mm / 2 = 64.5
	% If 72 x 72 matrix @ 3mm, then for coronal and sag calculate +- range as (64 - 1) slice spacings x 3mm / 2 = 94.5
%        iBT.what.disp.orient.slices = {64.5:-3:-64.5 94.5:-3:-94.5 -94.5:3:94.5};  % slice range corresponding to original own-space slices
	%
	% Notice that for axes with an even number of voxels, the slice 
	% selection will not include 0mm (as that would be between two slices).
	% Despite this, any sort of interpolation will introduce partial 
	% voluming so along with careful slice selection you probably also 
	% want to set iBT.what.disp.resample = 0 below (to force nearest neighbour resampling).
	%
	iBT.what.disp.statistic='T'; % Text label for the statistic being displayed
	iBT.what.disp.threshold.type =     {'p'       'FDRc'       't'       'li'}; % Type of threshold, as follows: 'p' ,'FWE' , or
	   % 'FWEc' - requires an array in iBT.what.disp.threshold.thresh with feature-selecting p and FWEc e.g. p<0.001 uncorrected FWEc<0.05: { [0.001 0.05] }
	   % 'FDRc' - requires an array in iBT.what.disp.threshold.thresh with feature-selecting p and FWEc e.g. p<0.001 uncorrected FDRc<0.05: { [0.001 0.05] }
	   % 'li'   - min valid Nvox in ROI based on laterality control group (will be gracefully ignored with a warning in log file if LI data not found)
	   % 't'    - raw statistic value (can specify this even if not actually a t-statistic - see also iBT.what.disp.statistic)
	  % The following three cells must have at least as many elements as iBT.what.disp.threshold.type; any extra elements are ignored:
	  iBT.what.disp.threshold.thresh = {0.001     [0.001 0.05] 0         -1}; % lower threshold for magnitude of statistics (0 for no threshold; -1 for type = 'li' described above)
	  iBT.what.disp.threshold.mini =   {0.000001  0.000001     0.000001  0.000001}; % minimum value on colour scale (must be greater than zero to see background )
	  iBT.what.disp.threshold.maxi =   {8         8            8         8}; % maximum value on colour scale
	iBT.what.disp.structural = 'auto'; % Structural image filename or auto detect (auto). If not fully qualified, will search in present folder, SPM.mat folder and iBT.who.sub{sub}.sess{ses}.disp.loc
	  iBT.what.disp.structuralLabel = 'Mean of EPI time series'; % Optional description of the structural image to be used (rather than displaying the filename)
	iBT.what.disp.contrast = 'auto';   % Statistical image(s) to display, e.g.'spmT_0003.img' (wildcards are allowed) or auto detect:
					% 'auto' to auto detect and display contrasts of interest EXCEPT those labelled with '-effect'
					% 'auto-' to auto detect and display all contrasts of interest, including those labelled with '-effect' 
					% '+effect' to display ONLY contrasts of interest labelled with '+effect' (i.e. usually the iBrain generated positive contrasts)
					% '-effect' to display ONLY contrasts of interest labelled with '-effect' (i.e. usually the iBrain generated negative contrasts)
	  iBT.what.disp.con = [0];  % If an auto or effect option is chosen above, consider only the particular contrast number(s) specified here,
	  			    % or [0] for all or negative numbers to count backwards from the final contrast present;
	  			    % for example if there are 10 contrasts, specifying [1 -2] will display only contrasts 1 and 9.
				    % Don't forget the toolbox usually will have created both positive and negative contrasts for each regressor of interest:
				    % specifying a contrast number of such a negative effect will result in it being displayed as if negative values are positive.
	iBT.what.disp.contrastMissingOK = 0;   % Ignore the contrast and return without error if a matching file is not found: 1(yes) 0(no)
	iBT.what.disp.copyHeaderInfo = 2;  % Make a copy of the header information in the destination folder: 2(yes unless OTHER or MELODIC), 1(yes always), 0(no)
	iBT.what.disp.copyStructural = 2;  % Make a copy of the structural image in the destination folder: 2(yes unless OTHER or MELODIC), 1(yes always), 0(no)
	iBT.what.disp.positive = 1; % Display positive values: 1(yes) 0(no)
	iBT.what.disp.negative = 1; % Display negative values: 1(yes) 0(no)
	iBT.what.disp.together = 2; % If both iBT.what.disp.positive and negative, create: 0(separate maps only), 1(default: one map with both + and - together), 2(both separate and together maps)
	iBT.what.disp.invert = 0; % Display positive values in cool colours, negative in warm colours: 0(no, default), 1(yes), 2(yes for -effect contrasts only)			  
				  % Note: If you specify 1 for both iBT.what.disp.positive and iBT.what.disp.negative and 2 for iBT.what.disp.invert
				  % then the display of +effect and -effect contrasts may appear to be identical (the only difference will be the 
				  % sign of the values on the colour scale). The option 2 is particularly useful when creating FDRc or FWEc maps 
				  % of -effects since only the positive tail can presently be displayed for cluster-corrected maps.
	iBT.what.disp.ROI.img = ''; % optionally specify a fully-qualified filename of a region-of-interest image to highlight a region on the image
	iBT.what.disp.resample = 0; % Resampling order for image (see hold argument to spm_sample_vol) - 0 = nearest neighbour, 1 (default) = trilinear,
				    % 2->127 = Higher order Lagrange (polynomial), -127 - -1 =  Different orders of sinc interpolation.
        iBT.what.disp.postscript = 0;      % PostScript file: 0 (none), 1 (truncate the existing file) or 2 (append to the existing file)
	iBT.what.disp.hideName = 0;	       % use the iBT.who.sub.ID rather than subject name for display headings (see also hideHeaderID) 1(yes) 0(no)
	iBT.what.disp.hideHeaderID = 0;    % Useful with hideName if the subject ID field in the image header also contains the name:  1(yes) 0(no)
% End of iBT.what.disp.do section


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% section 3: defaults
%
% Assumptions/options in the stages...
% bits you probably don't need to change
% (some settings here may not actually be used
%  if the relevant flag above has not been set)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Preprocessing
	iBT.what.pre.interleaved = 4;	% Slice ordering scheme: 0 = Ascending sequential (i.e. not interleaved), 
       					% 1=single ascending interleaved (e.g. 5 slices would be: 1,3,5,2,4)
       					% 2=double ascending interleaved (i.e. 1, 5, 9, ..., 4, 8, 12, ..., 3, 7, 11, ..., 2, 6, 10)
       					% 3=single ascending interleaved with second-bottom slice acquired first e.g. 5 slices would be: 2,4,1,3,5
       					% 4=same as option 1 if total number of slices is odd, otherwise option 3. (As can be the case for Siemens DICOM Mosaic files)
					% 10=Descending sequential (i.e. not interleaved), 
       					% 11=single descending interleaved. e.g. 5 slices would be: 5,3,1,4,2 
       					% 13=single descending interleaved with second-top slice acquired first e.g. 5 slices would be 4,2,5,3,1
       					% 14=same as option 11 if total number of slices is odd, otherwise option 13.					
					% -1=Use explicitly specified order or times from iBT.what.pre.slice_order (see below)				
	% Note in comments above slice numbers refer to the order as read by spm_slice_vol(Vin,spm_matrix([0 0 slice_number]),Vin.dim(1:2),1)
	% (as per code in spm_slice_timing(), documentation for which in spm8 describes slice_number as position of a slice within the image file)

	% iBT.what.pre.slice_order = [1,3,5,2,4]; % If none of the iBT.what.pre.interleaved options above suit, then you can specify
						  % either an explicit slice order or slice times (in milliseconds) here. 
						  % Note: Specifying slice times is only supported by SPM12 or later.
			
	iBT.what.pre.slice_time_extra_gap = 0.0; % Additional dead-time within the TR at the end of each volume. Set to
       	% 0 for continuous evenly spaced scanning. Otherwise the time between the last slice of one volume and the 
	% first slice of the next is slice_time_extra_gap seconds longer than the time between slices within a volume.
	
	iBT.what.pre.target_time= 'middle'; % Set to 'first' or 'middle' (for slice timing: 'first' picks the slice acquired first in time in the TR,
       					  % middle picks the slice acquired nearest to the middle of the TR; the resulting anatomical slice order 
					  % position is documented as "ref_slice =" in the matlab_iBT_preprocess*.log file)     

	iBT.what.pre.wild.input='*.dcm';         % wildcard for input images (e.g. DICOM)
	%iBT.what.pre.wild.input='MR*';           % wildcard for input images (e.g. DICOM)
	%iBT.what.pre.wild.input='*.nii.gz';      % wildcard for input images (e.g. BIDS)

	if (iBT.what.pre.iBrainConvert == 0) && (iBT.what.pre.DICOMconvert ~= 0) % Then we're asking SPM to do the conversion
		iBT.what.pre.wild.raw='f*-????-?????-??????-??.img'; % wildcard for raw NIfTI images produced by SPM
	else
		iBT.what.pre.wild.raw='0?????.img';	% wildcard for raw images produced by iBrain
	end
	iBT.what.pre.wild.ref='_median-COM_*.img';   % wildcard for realignment target
	iBT.what.pre.wild.slice  = cat(2, 'a', iBT.what.pre.wild.raw);	% wildcard for slice timing corrected images
	if iBT.what.pre.SliceTiming == 0
		iBT.what.pre.wild.realign = cat(2, 'r', iBT.what.pre.wild.raw);	% wildcard for realigned images
	else
		iBT.what.pre.wild.realign = cat(2, 'ra', iBT.what.pre.wild.raw);	% wildcard for realigned slice-time corrected images
	end

       iBT.what.pre.sessions_together	= 0;    
        % 0 = realign sessions independently (but see also iBT.what.pre.norm.intra.do)
	% 1 = realign all sessions to a target in the subject's master session (iBT.who.sub{sub}.MasterSession)
	% Note: An alternative multi-session approach is to use iBT.what.pre.norm.intra.do, which
	%       realigns independently within sessions and then spatially normalises across 
	%	sessions (which may be a more powerful approach, as intra-session realignment should be tighter). 
	%	Whilst it is possible to do both iBT.what.pre.sessions_together and iBT.what.pre.norm.intra.do
	%	it is probably not a good idea because with iBT.what.pre.sessions_together you 
	%	loose the potential advantage of tighter intra-session alignment.

       iBT.what.pre.realign.write.interp = 7; % Interpolation: 0 = Nearest Neighbour, 
       					  % 	1  = trilinear (SPM2 default), 
					  % 	2= 2nd degree B-spline, ..., 7 = 7th degree B-spline
       iBT.what.pre.realign.write.wrap = [0 1 0];% Way to wrap images 
       					     % [0 0 0] = none (SPM2 default)
					     % [0 1 0] = images wrap in Y dimension only
					     
       % The following two items are only used if iBT.what.pre.norm.intra.do is true:
       iBT.what.pre.norm.intra.niterations = 3;  % the number of iterations for within-subject registration
       iBT.what.pre.norm.intra.strategy = 2;  % Strategy for intra-subject normalisation 
       		% Strategy 1 determines the final warp from affine-registered space
		% Strategy 2 inverts the initial affine transform and warps from near-own space
		% Strategy 2 seems to work best (at least for our GE images).
 
	switch(iBT.what.SpmVersion), %% Initialise some variables with SPM defaults - we will then change some fields later
	  case {'SPM2','SPM5'}
		iBT.what.pre.norm.write=defaults.normalise.write;
		iBT.what.pre.norm.estimate=defaults.normalise.estimate;
	  case {'SPM8'}
		iBT.what.pre.norm.write = spm_get_defaults('normalise.write');
		iBT.what.pre.norm.estimate = spm_get_defaults('normalise.estimate');
          otherwise % SPM12 or later
		iBT.what.pre.norm.write = spm_get_defaults('old.normalise.write');
		iBT.what.pre.norm.estimate = spm_get_defaults('old.normalise.estimate');
	end % switch(iBT.what.SpmVersion)
	
       %% Now change some fields to what we really want:
       iBT.what.pre.norm.estimate.nits = 16; %Number of non-linear iterations (ignored if iBT.what.pre.norm.do is 2 or 3)
       iBT.what.pre.norm.write.vox = [2 2 2]; %vox size in MNI space (SPM2 default is 2mm x 2mm x 2mm)
       iBT.what.pre.norm.write.interp = iBT.what.pre.realign.write.interp;   % See above
       iBT.what.pre.norm.write.wrap = [0 0 0]; % After realignment the images may no-longer be in same plane as acquisition, so can't wrap anymore.
       iBT.what.pre.norm.write.bb = [[-90 -126 -72];[90 90 108]]; % Spatial Normalisation bounding box 
					  % The SPM2 default is [[-78 -112 -50];[78 76 85]];
					  % whilst this matches the template: [[-90 -126 -72];[90 90 108]];

%% Analysis/statistics
       iBT.what.stats.subdir = [iBT.what.SpmVersion '_stats'];% analysis subdirectory (created automatically within iBT.what.where.awd)
       				       % Other subdirectories are also created as required for sessions, subjects and group
       if iBT.what.stats.fc.do ~= 0,
         iBT.what.stats.subdir = [iBT.what.stats.subdir '_fc'];
       end
       iBT.what.stats.subdirZeroOffset = 0;% Append _+0 to subfolder names when time offset is zero: 1 = yes, 0 = no.
       iBT.what.stats.number_dirs = 1; % prepend NN_ to subfolder names, where NN is the session count starting from 01.
       iBT.what.stats.tasks_text_max_length = 30; % If the label iBT.what.stats.tasks becomes longer than this, it will be truncated.
       iBT.what.stats.r_wild = cat(2, 'sra', iBT.what.pre.wild.raw);	% wildcard for non-normalised images to analyse

       iBT.what.stats.n_wild = cat(2, 'swa', iBT.what.pre.wild.raw);	% wildcard for spatially-normalised images to analyse

       iBT.what.stats.denoised.folder = fullfile('swa_all.ica','denoised_imgs');
       iBT.what.stats.denoised.n_wild = 'dswa*.img';%  wildcard for denoised spatially-normalised images to analyse

       iBT.what.stats.mc.fmriprep = iBT.what.pre.fmriprep.done; % Read motion correction parameters from fmriprep's .tsv file: 1(yes); 0(No)
          % see also iBT.who.sub{sub}.sess{ses}.fmriprep.wild
       iBT.what.stats.mc.wild = 'rp_*.txt'; % wildcard for mc parameters from SPM pre-processing (used only if iBT.what.stats.mc.fmriprep is 0)

	% The within-brain mask file for each session is assumed located in iBT.who.sub{n}.sess{n}.loc,	
	% and the filename is usually determined automatically based on 
	% the iBT.what.stats.r_withinBrainMask and iBT.what.stats.n_withinBrainMask variables set above.
    % This can be overridden by either uncommenting the lines below, or using the
	% session-specific iBT.who.sub{sub}.sess{ses}.wild.*_ExplicitMask variables above.
	%iBT.what.stats.r_ExplicitMask.wild = 'iBrainMask_mean.img'; % Only uncomment and set if you want to override automatic filename determination
	%iBT.what.stats.n_ExplicitMask.wild = 'iBrainMask_wmean.img'; % Only uncomment and set if you want to override automatic filename determination

       if iBT.what.pre.Realign == 0,
       		iBT.what.stats.mc.mp = 0;    % include movement parameters as regressors in design: 1(yes; default if not specified); 0(no)
       else
       		iBT.what.stats.mc.mp = 1;    % include movement parameters as regressors in design: 1(yes; default if not specified); 0(no)    
       end
       iBT.what.stats.mc.extra = 0; % specify whether to include 2nd order polynomial
                                    % expansion of motion regressors: 1(yes) 0(no)
				    % (requires iBT.what.stats.mc.mp = 1)
       iBT.what.stats.mc.rej = 1.0;   % specify whether to automatically reject volumes affected by gross scan-to-scan motion.
                                % 0 = don't reject
                                % n = reject motion greater than "n" mm (via inclusion of scan-nulling regressors)
         iBT.what.stats.mc.rejN = 4; % Number of volumes to reject when gross motion occurs (more than 1 allows for T1 effects).		
         iBT.what.stats.mc.metric = 'FramewiseDisplacement'; % Metric to use for motion rejection. Either 'FramewiseDisplacement' or 'DeltaOriginDistance'
       iBT.what.stats.parametric_modulation_by_separation = 0;      % Include parametric modulation by the time separation between an event and the previous one; specify the order - eg
                                % 0 = no modulation
                                % 1 = 1st order (linear)
                                % 2 = 2nd order (quadratic)
       if iBT.what.stats.fc.do == 1, iBT.what.stats.orth_regressors = 2;
       else iBT.what.stats.orth_regressors = 0; end % Orthogonalise effects of interest?: 
		% Note these options are in addition to SPM's automatic delay and disperison orthogonalisation in SPM5 or later
		 % 0 = Do no additional orthogonalisation.
		 % 1 = Yes, within main effects only (e.g. each main effect regressor will be unchanged, 
		 %     delay and dispersion would change). This already happens automatically in SPM5 or later. 
		 %     It is usually desired when you model effects with HRF plus time and/or dispersion
		 %      derivatives, to ensure that all that can possibly be modelled by the HRF terms end
		 %      up in the HRF columns (so you can still use t-tests to look at them).
		 % 2 = Yes, for all regressors in original order (thus the 1st regressor will be unchanged)
		 %     This can be used for functional connectivity if we specify the timecourses of interest
		 %       last in the design matrix so they will be changed such that all preceding effects are 
		 %       regressed out. It might also be occasionally useful for clinical application of conventional
		 %       block or event-related designs if one is prepared to tolerate false positives
		 %       due to motion covarying with task. However, see also option 2.1 below.
		 % 2.1 = Yes, same as option 2 above, but exclude the very last regressor 
		 %       (e.g. Use instead of 2 if the last regressor in the model is 
		 %             a constant term and you want to keep it that way )
		 % 3 = Yes, for all regressors in reverse order (so first regressor will be changed the most). Could be
		 %    used for conservative analysis of block or event-related designs when you want to make sure no
		 %    non-interesting variance ends up in the regressor of interest, however option 4 below is probably
		 %    better, especially if you have delay or dispersion terms as you probably don't want to regress
		 %    those out of the main effect regressor. Note: this option 3 is not designed for functional
		 %    connectivity (FC) analysis (for theoretical reasons) and you shouldn't even try it for FC in practice
		 %    due to a software limitation that always assumes the presence of a block effect.
		 % 4 = Yes, with all regressors of no interest orthogonalised before regressors of interest, but otherwise 
		 %    in original design matrix order. This provides a conservative analysis of block or event-related
		 %    designs as well as connectivity, when you want to make sure no non-interesting variance ends
		 %    up in the regressors of interest. Unlike option 3, option 4 is also suitable when there are
		 %    additional basis functions of interest, including delay or dispersion. For designs with a block
		 %    effect see also option 4.1 below.
		 % 4.1 = Yes, same as option 4 above, but exclude session block (constant) regressor from orthogonalisation.
		 %
       % Basis functions and timing parameters
%      iBT.what.stats.SPM.xBF.name       = 'hrf (with time and dispersion derivatives)';% You probably should also set iBT.what.stats.orth_regressors = 1 above.
       iBT.what.stats.SPM.xBF.name       = 'hrf';
       			    % This can be any of the following:
       			    %'hrf'
			    %'hrf (with time derivative)'
                            %'hrf (with time and dispersion derivatives)'
                            %'Fourier set'
			    %'Fourier set (Hanning)'
			    %'Gamma functions'
			    %'Finite Impulse Response'
       iBT.what.stats.SPM.xBF.length     = 32;          % support of basis set in seconds
       iBT.what.stats.SPM.xBF.order      = 1;           % order of basis set
       iBT.what.stats.SPM.xBF.T          = 16;          % number of time bins per scan
       iBT.what.stats.SPM.xBF.T0         = 8;           % first time bin (see slice timing)
       % iBT.what.stats.SPM.xBF.UNITS has been replaced by iBT.what.stats.onset_dur_units set near start of this file   
       iBT.what.stats.SPM.xBF.Volterra   = 1;           % OPTIONS: 1|2 = order of convolution
       iBT.what.stats.SPM.xGX.iGXcalc    = 'none'; 	   % global normalization: OPTIONS:'Scaling'|'None'
       if iBT.what.stats.fc.do == 0,
         iBT.what.stats.SPM.xVi.form       = 'AR(1)'; % intrinsic autocorrelations: OPTIONS: 'none'|'AR(1)'|'FAST'
              % 'AR(1)' here means an AR(1) process with alpha=0.2. Since SPM2 this is has been the default for any specified
	      % string here other than 'none' and (since SPM12) 'FAST'. Karl Friston's SPM email list posts of 2003-09-30 
	      % and 2016-12-12 are instructive: The current default yields an almost identical result as SPM99's old 'AR(1)+w'  
	      % option (i.e. AR(1) process plus white noise). If you actually want to change the alpha for the AR(1) process
	      % you can apparently specify a floating point number or array here instead of a string. You can verify how SPM has
	      % interpreted this input by checking SPM.xVi.form in the SPM.mat file after the design matrix has been configured.
	      % In SPM12 a new option 'FAST' was introduced; it is more appropriate for particularly short TR's (less than a
	      % second) and has therefore been used in multiband studies. See also https://doi.org/10.1002/hbm.24218
       else
       	 iBT.what.stats.SPM.xVi.form       = 'none';
       end
       iBT.what.stats.SPM.xX.K.HParam    = 128;        % low frequency confound: high-pass cutoff (secs) [Inf = no filtering]

       iBT.what.stats.clobber = 0; % Default 0 (exit with error if SPM.mat already exists). Note: overwriting existing 
           % files is not recommended, because if clobber is set and estimation files exist, iBT will still create a
           % fresh SPM.mat but SPM will eventually prompt interactively via a GUI pop-up at the design estimation stage,
           % and you will need to click continue (you would need to edit SPM's spm_spm.m to avoid that).
       iBT.what.stats.MAT64bit = 0; % 1(yes) 0(ignored); Not required for SPM12r7716 or later, as dynamically appplied when necessary.
           % Set to 1 to force .mat file format -v7.3 to allow variables larger than 2GB on 64-bit computers
           % (only necessary if you have a lot of images in the design. e.g. a very long multiband short-TR study)

%% Functional Connectivity options
    	iBT.what.fc.LParam = 1/0.08; % low-pass filter cut-off (in seconds)
    	iBT.what.fc.HParam = 1/0.01; % high-pass filter cut-off (in seconds) 

%%  Laterality
	% iBT.what.li.SummaryPlot.show100 = 0; % 1(yes, display LIx100 (i.e. %) on the body of the summary plot) 0(no, display regular LI on the body of the plot (default) ) 
	iBT.what.li.nvox_step = 10; % Increment for number of voxel threshold
	iBT.what.li.thresh_step = 0.1; % Increment for t-value threshold
	% If iBT.what.li.do_graph is set, the following options can be used change defaults:
	% iBT.what.li.lowNpercentValid = 90; % Minimum percentage (default 95) of control subjects that must not yet have exhausted all positive voxels if jb test is to be performed
	% iBT.what.li.lowNpercentOffCeiling = 95; % Percentage of subjects that must have |LI| less than ceiling in "valid" region. Set to 0 for no constraint (default)
	% iBT.what.li.ceiling = 1.0; % Ceiling LI value for lowNpercentOffCeiling test above. Default = 1.0
	% iBT.what.li.jb_alpha = 0; %  Alpha value for the Jarque-Bera normality test. Default = 0.05. Set to 0 for no normality constraint. 
	% iBT.what.li.do_tgraph=1; % In addition to the default LI vs Nvoxel plots, also plot LI against t-threshold,
	                       % (these were used in the paper for comparison - you probably don't want this!): 1(yes) 0(no)
	% iBT.what.li.PlotJB=0; % Plot a representation of the Jarque-Bera values on the full plot (they will be green)
	% iBT.what.li.maxNvox=0; % full nvox plot maximum value, 0=Unlimited
	iBT.what.li.maxT=10; % full t-thresh plot maximum value, 0=Unlimited 	  

	% iBT.what.li.errorbars=1; % Plot group 95% CI as errorbars: 1(yes) 0(no,default)
	% iBT.what.li.CI95shading=0.85; % Shade outside group 95% CI (Grey value of shading ranging from 0=black to 1=none)
	% iBT.what.li.CI99shading=0.8; % Shade outside group 99% CI in full plot (Grey value of shading ranging from 0=black to 1=none) 
	% iBT.what.li.InvalidShading=0.9; % Shade outside valid area (Grey value of shading ranging from 0=black to 1=none) 
	iBT.what.li.FullPlot.AllY = 1; % Force full plot yrange from -1 to 1: 1(yes) 0(no - use automatic range)
	iBT.what.li.SummaryPlot.AllY = 1; % Force summary plot yrange from -1 to 1: 1(yes) 0(no - use automatic range)
				    % (this is forced to 1 if iBT.what.li.conclusion.do==1 to provide room for text)
	iBT.what.li.SummaryPlot.in_range_only=2; % If there is a valid range, then plot summary within that range?
		% -1(no, plot summary over same range as full plot).
		% 0(no, plot summary from 0 to max of valid range)
		% 1(yes, plot summary within valid range only).
		% 2(no, plot a portion of the invalid range as well ).
	  % The following settings determine what portion of the invalid range is
	  % also displayed if iBT.what.li.summary_plot_in_range_only=2:
	  iBT.what.li.SummaryPlot.lower_range_fraction = 2/3; % Plot this proportion of the lower invalid range (0 = none, 1 = all) 
	  iBT.what.li.SummaryPlot.upper_range_fraction = 2/3; % Plot whilst this fraction of control subjects still has data (0 = plot all)
	% iBT.what.li.RGB.GroupMean=[0 0 0]; % (all 0 is black) % Colour of the control group mean plot (default [0 1 1] which is cyan)
	 % iBT.what.li.LineStyle.GroupMean='-' % Style of the control group mean plot (default '-' which is a solid line)
	% iBT.what.li.RGB.GroupControls=[0.1 0.1 0.1] % (all 0.1 is very dark grey) % Colour of subjects in the control group (default [0.4 1 1] which is a bit lighter cyan)
     % iBT.what.li.LineStyle.GroupControls='--' % Line style of subjects in the control group (default '--' which is dashed)
	%iBT.what.li.RGB.Individual=[1 0 0]; % Colour of the individual subject (default [1 0 0] which is red)
	 %iBT.what.li.LineStyle.Individual='-';  % Line style of the individual subject (default '-' which is a solid line)
	%iBT.what.li.LineWidth.Default=2; % Default if not specified is 1.
	 %iBT.what.li.LineWidth.Individual=2; % Default if not specified is 1.
	%iBT.what.li.SummaryPlot.LineWidth.Default=3; % Default is iBT.what.li.LineWidth.Default
	 %iBT.what.li.SummaryPlot.LineWidth.Individual=3 % Default is iBT.what.li.SummaryPlot.LineWidth.Default
	%iBT.what.li.SummaryPlot.LIpoint=1; % Plot a marker on summary plot at point the stated LI is determined for the individual: 1(yes), 0(no, default) 
	 %iBT.what.li.SummaryPlot.RGB.LIpoint=[1 0 0]; % Colour of the LI point marker on the summary plot; default is iBT.what.li.RGB.Individual
	 %iBT.what.li.SummaryPlot.LineWidth.LIpoint = 3; % Default is 1
     %iBT.what.li.SummaryPlot.MarkerSize.LIpoint=12; % Default is 5
		 	
	 %iBT.what.li.PlotGroupOnly=1;% Don't plot the individual - just plot the group (was useful for a figure for the paper).
	                          % This also enables plotting all group data on the summary plot in addition to the full plot.

	  %iBT.what.li.FullPlot.Title=['Enter custom plot title here'];% Uncomment to force title of the plot.
	  %iBT.what.li.FullPlot.fileIDstring=['Enter custom filename here'];% Uncomment to force filename of the plot.
	  iBT.what.li.FullPlot.Box=1; % include a box with tick marks around the plot, 1(yes) 0(no)
	  %iBT.what.li.SummaryPlot.Title=iBT.what.li.FullPlot.Title;% Force title of the plot.
	  %iBT.what.li.SummaryPlot.fileIDstring=iBT.what.li.FullPlot.fileIDstring;% Uncomment to force filename of the plot..
	  iBT.what.li.SummaryPlot.Box=1; % include a box with tick marks around the plot, 1(yes) 0(no)
	  %iBT.what.li.SummaryPlot.RGB.GroupMean=[0.7 0.7 0.7]; % Colour of the control group mean on the summary plot (default same as detailed plot)
	  %iBT.what.li.SummaryPlot.LineStyle.GroupMean='--'; % Style of the control group mean on summary plot (default same as detailed plot)	
	  %iBT.what.li.SummaryPlot.typicalString=' ';  % Default if commented out is 'Conclusion: typical'
	  %iBT.what.li.SummaryPlot.atypicalString=' '; % Default if commented out is 'Conclusion: atypical'

%%  Display
	iBT.what.disp.show.name = 1;
	iBT.what.disp.show.ID = 1;
	iBT.what.disp.show.date = 1;
	iBT.what.disp.show.voxelSize = 0; % Display original scanner acquisition voxel sizes: 1(yes, default) 0(no)
	iBT.what.disp.show.procVoxelSize = 0; % Display processed volume voxel sizes % 1(yes) 0(no, default)
	% iBT.what.disp.show.mrej = 1; % Display effective number of task and rest scans included after motion rejection regressors are taken into account.  1(yes, default) 0(no)
	if iBT.what.stats.subjects.do == 1,
		iBT.what.disp.show.task = 0;
		iBT.what.disp.show.conName = 1;
		iBT.what.disp.fontsize1 = 13;
	else
		iBT.what.disp.show.task = 1;
		iBT.what.disp.show.conName = 0;
	 	iBT.what.disp.fontsize1 = 15;
	end
	% iBT.what.disp.fontsize2 = 11;
	iBT.what.disp.show.thresh = 1;
	iBT.what.disp.show.warp = 1; 
	iBT.what.disp.show.smooth =1;
	iBT.what.disp.show.colourbar=1;
	iBT.what.disp.show.LR = 1; % Display a Left or Right indicator to the left of the axial and coronal image montages 0(no, default) 1(yes)
	iBT.what.disp.transparency = 0;  % Force a fixed transparency (range from 0=default(opaque), 1 = invisible).
		% The default is a value dependent on the threshold range such that very low
		% threshold images appear opaque)
	iBT.what.disp.ROI.colour = [0.19 0.0 0.38]; % RGB colour of ROI, a triplet of values between 0 and 1; e.g. [0.19 0 0.38] is purple.
	iBT.what.disp.ROI.transparency = 0.1; % transparency of ROI
	iBT.what.disp.threshold.write_t_value_file = 1; % Create a file indicating t for requested p in iBT.what.disp.threshold.thresh (can be used by some iBrain functions)
 	iBT.what.disp.threshold.structural.low = 0; % Optional parameter to limit the lowest allowed adaptive value of the grey range (e.g. set to zero to ignore negative values)
	% iBT.what.disp.threshold.structural.high = 10000; % Optional parameter to limit the highest adaptive value of the grey range for structural image display, potentially
                                                        % useful if image is contaminated by outlier high-intensity voxels.
	% iBT.what.disp.threshold.structural.min = 0; % Optional parameter to force the low value of the grey range for structural image display
	% iBT.what.disp.threshold.structural.max = 10000; % Optional parameter to force the high value of the grey range for structural image display

